### PR TITLE
vm.sh: Add iptables DNAT rules for rootless podman

### PR DESCRIPTION
**Pull request by 0xFelix**
This adds iptables DNAT rules for rootless podman. Because traffic is
originating from the loopback adapter when using rootles podman /
slirp4netns, the existing iptables rules did not apply and
'make cluster-up' was failing on rootless podman. This patch checks
whether a rootless container is used and adds the corresponding
iptables rules.

### CODE REVIEW

**Comment by EdDev** [comment]
@0xFelix , thank you for this change.

Could we check at this stage if we are in a rootful or rootless container? If we could, then we could adjust each with its own proper focused configuration.

I think this addition will not harm the rootful run, but we better check nevertheless (that we did not increased the run time).

**Review by EdDev — APPROVED** [review]
Nice! Thank you!!

**Review by enp0s3 — COMMENTED** [review]
/approve

**Pull request merged**
