### PR TITLE
kind: Use quay registry image

### PR DESCRIPTION
**Pull request by oshoval**
Avoid docker rate limit.
Image supports multi arch:
amd64, arm64

Signed-off-by: Or Shoval <oshoval@redhat.com>

### CODE REVIEW

**Comment by oshoval** [comment]
@zhlhahaha 
Hi, can you please confirm it works on arm64?

**Comment by oshoval** [comment]
Failure is not related to this PR

**Comment by zhlhahaha** [comment]
> @zhlhahaha Hi, can you please confirm it works on arm64?

Ok

**Comment by zhlhahaha** [comment]
> @zhlhahaha Hi, can you please confirm it works on arm64?

It works well on Arm64 server.

**Comment by oshoval** [comment]
Something is wrong with the VM based providers, not related to this PR
but looks we need to know about it

**Comment by oshoval** [comment]
/hold

so it will stop retest maybe, the VM lanes have problems
not related to this PR

**Pull request merged**
