### PR TITLE
Simplify image modifications of cluster-provision/images/vm-image-builder

### PR DESCRIPTION
**Pull request by rmohr**
Condense the image creation process in cluster-provision/images/vm-image-builder to the following steps:

## Building

```bash
./build-containerdisk.sh example
```

## Publish

```bash
./publish-containerdisk.sh example myregistry/myimage:mytag
```

Environment variables do not need to be set anymore. Every directory, like the `example` directory contain now three files (cloud-config, os-variant and image-url) which contains all necessary information to build the images.

The README.md file contains the updated instructions.

### CODE REVIEW

**Comment by rmohr** [comment]
@davidvossel @ormergi when you find the time. Just want to get done with a few old PRs.

**Review by davidvossel — APPROVED** [review]
/lgtm
/approve

**Comment by rmohr** [comment]
> /lgtm
> /approve

There was a CI outage when you wrote this. Manually set the labels.

**Pull request merged**
