### PR TITLE
cnao, provision, Bump k8s-1.19/1.20/1.21 cnao to v0.56.0

### PR DESCRIPTION
**Pull request by oshoval**
CNAO version v0.54.0+ has a crucial fix for Kubemacpool / kubevirt sync [1]
Without it, kubemacpool will add the VM finalizer, but the kubemacpool manager won't restart
resulting in the finalizer not removed from the VM, as seen on [2].

[1] https://github.com/k8snetworkplumbingwg/kubemacpool/pull/292
[2] https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-1.21-sig-network/1407559103336681472

### CODE REVIEW

**Review by RamLavi — APPROVED** [review]
/lgtm

**Comment by oshoval** [comment]
Thanks Ram
@qinqon @phoracek can you take a look please?
locally it solved the problem of k8s-1.21 and we saw in the kmp logs that this is indeed the problem
(no manager restart appeared, and the VM was marked for deletion and still had the finalizer)

**Comment by oshoval** [comment]
Thanks,
following https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/publish-kubevirtci/1407694874735546368
once its done will create a bump

**Pull request merged**
