### PR TITLE
Fix docker version issues, bump k8s-1.17 micro and temporarily disable dontaudit on k8s-1.17

### PR DESCRIPTION
**Pull request by jean-edouard**

### CODE REVIEW

**Comment by dhiller** [comment]
/lgtm
/hold

I guess you need to remove the temporary disablement.

**Comment by jean-edouard** [comment]
@dhiller well it's not *that* temporary... It is there to ensure that no flaky test fails because of SELinux. The idea is to run tests with that for a few days to collect artifacts info and then revert the change. If that's not acceptable though, I can remove the commit.

**Comment by dhiller** [comment]
> @dhiller well it's not _that_ temporary... It is there to ensure that no flaky test fails because of SELinux. The idea is to run tests with that for a few days to collect artifacts info and then revert the change. If that's not acceptable though, I can remove the commit.

OK, understood. SGTM. Still holding for pushing and updating image shas.

**Comment by dhiller** [comment]
Meh, jobs are failing just due to quay outage :-(

**Comment by rmohr** [comment]
Do we need the same for 1.18?

**Comment by jean-edouard** [comment]
@rmohr which part?

**Pull request merged**
