### PR TITLE
Run unit tests

### PR DESCRIPTION
**Pull request by aerosouund**
**What this PR does / why we need it**:

With moving bash opts to golang, unit tests were introduced for every opt. But they aren't being run as a part of any CI process
This PR fixes all broken tests and changes the `make test-gocli` command of the gocli to run all tests in the project

**Checklist**

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [x] PR: The PR description is expressive enough and will help future contributors
- [x] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by aerosouund** [comment]
cc: @xpivarc @dhiller @brianmcarey

**Review by brianmcarey — COMMENTED** [review]
Which CI job will these tests be run in?

**Comment by aerosouund** [comment]
@brianmcarey 
Test provision manager

**Comment by brianmcarey** [comment]
> @brianmcarey Test provision manager Its what runs the make test command

Ok maybe we should update the job name to match the more generic nature of what is being run.

**Comment by dhiller** [comment]
> > @brianmcarey Test provision manager Its what runs the make test command
> 
> Ok maybe we should update the job name to match the more generic nature of what is being run.

Good point - however a separate task from this PR, no?

Suggestion: how about changing `make all` to include `test` target, since `check-gocli` calls it anyway [1]? Then we could get rid of the other presubmit job?

[1]: https://github.com/kubevirt/project-infra/blob/2aa7c952a9ae348c2c4b51e87c803b8a45c0730f/github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml#L332

**Comment by dhiller** [comment]
> > Ok maybe we should update the job name to match the more generic nature of what is being run.
> 
> Yes, but where should this change take place ? I'm not aware of how you can change stuff in prow (job configs, names.. etc)

it's inside `project-infra` folder `github/ci/prow-deploy/files/jobs` - there's the job definitions (see above link for the definition of `check-gocli`)

**Comment by dhiller** [comment]
> > > @brianmcarey Test provision manager Its what runs the make test command
> > 
> > 
> > Ok maybe we should update the job name to match the more generic nature of what is being run.
> 
> Good point - however a separate task from this PR, no?
> 
> Suggestion: how about changing `make all` to include `test` target, since `check-gocli` calls it anyway [1](https://github.com/kubevirt/project-infra/blob/2aa7c952a9ae348c2c4b51e87c803b8a45c0730f/github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml#L332)? Then we could get rid of the other presubmit job?

@brianmcarey WDYT? ^^

**Comment by brianmcarey** [comment]
> > > > @brianmcarey Test provision manager Its what runs the make test command
> > > 
> > > 
> > > Ok maybe we should update the job name to match the more generic nature of what is being run.
> > 
> > 
> > Good point - however a separate task from this PR, no?
> > Suggestion: how about changing `make all` to include `test` target, since `check-gocli` calls it anyway [1](https://github.com/kubevirt/project-infra/blob/2aa7c952a9ae348c2c4b51e87c803b8a45c0730f/github/ci/prow-deploy/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml#L332)? Then we could get rid of the other presubmit job?
> 
> @brianmcarey WDYT? ^^

Sounds good to me - the lane should also be set to always run and be required too.

**Comment by aerosouund** [comment]
@brianmcarey @dhiller 
will do

**Comment by aerosouund** [comment]
@brianmcarey @dhiller 
I have changed the check gocli job to run the tests by adding a new target called `test-gocli` and modified the job definition to be required: https://github.com/kubevirt/project-infra/pull/3703

**Review by brianmcarey — COMMENTED** [review]
@aerosouund  - this looks good but you mention `make test` in the PR description but you are adding a new make target - can you update the PR description? or is there any reason why the test make target could not be used for this?

**Comment by xpivarc** [comment]
@aerosouund Do we have a unit test lane? Can we configure it?

**Comment by aerosouund** [comment]
@brianmcarey It can be used, but the reason why i didn't use it is that its called in the test provision-manager lane. and i didn't want the users seeing unit test failures when they expect provision manager results. but it does however make sense to run the cli test before the provision manager. because if the cli code is faulty then the provision manager itself is at risk of not working.

I have updated the PR to mention the new target name.

@xpivarc The goal is for this to run as part of the check-gocli lane. it seems fitting that checking the gocli also checks if its tests are passing.
let me know if you have a different opinion

**Comment by xpivarc** [comment]
> @xpivarc The goal is for this to run as part of the check-gocli lane. it seems fitting that checking the gocli also checks if its tests are passing. let me know if you have a different opinion

That is fine as they should be fast.

**Comment by aerosouund** [comment]
Yes, as you can see they ran successfully in this run on the check-gocli job on this PR and took no time

**Review by brianmcarey — COMMENTED** [review]
/approve

thanks @aerosouund

**Review by brianmcarey — COMMENTED** [review]
/lgtm

**Pull request merged**
