### PR TITLE
Drop k8s support for <= 1.18

### PR DESCRIPTION
**Pull request by dhiller**
/cc @rmohr @fgimenez @davidvossel

### CODE REVIEW

**Comment by rmohr** [comment]
/lgtm
/approve
/hold

Needs the 1.18 lane removed first

**Comment by rmohr** [comment]
The istio binary again. @rhrazdil you had the idea to host it on our storage, right?

**Comment by rhrazdil** [comment]
@rmohr It will be my tomorrow's project

**Comment by dhiller** [comment]
> /lgtm
> /approve
> /hold
> 
> Needs the 1.18 lane removed first

Please see 
https://github.com/kubevirt/project-infra/pull/1371/files

**Comment by dhiller** [comment]
/unhold

old lanes were removed by  https://github.com/kubevirt/project-infra/pull/1371

/retest

**Pull request merged**
