### PR TITLE
Add k8s-1.26 with centos 9 base

### PR DESCRIPTION
**Pull request by dhiller**
We add an explicitly marked 1.26 provider having the `centos9` label in order to distinguish it for the change of the node operating system that is happening.

### CODE REVIEW

**Comment by dhiller** [comment]
@brianmcarey FYI

**Comment by dhiller** [comment]
I'll create a check-provision for this soon

**Comment by dhiller** [comment]
check-provision looks good: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirtci/945/check-provision-k8s-1.26-centos9/1610664918191706112

**Review by brianmcarey — APPROVED** [review]
/lgtm

/approve

**Pull request merged**
