### PR TITLE
Bump calico to v3.18.0

### PR DESCRIPTION
**Pull request by qinqon**
There are some calico readiness probe problems and an some WARNINGS
appear at calico-node pods, looks like we are using a calico version
that does not deal correctly with those issue at least at cosmetic
level. This change bumps calico to have the fix [1]

[1]: https://github.com/projectcalico/felix/commit/a3621e3c3aa46cd8d3b66c9eb74734e84d8ddc5c

### CODE REVIEW

**Comment by qinqon** [comment]
@fedepaol

**Review by ormergi — COMMENTED** [review]
Hey do you plan to bump it for SRIOV provider?
https://github.com/kubevirt/kubevirtci/tree/master/cluster-up/cluster/kind/manifests

**Comment by rmohr** [comment]
/lgtm
/approve

/hold

Feel free to unhold once you are sure it works like expected. Regarding to sriov, I did not see the issue there. Not sure if we need to bump it right away.

**Review by fgimenez — APPROVED** [review]
/lgtm

**Comment by qinqon** [comment]
@ormergi can you put in place a test PR to run this on kubevirt lanes ?

**Review by fgimenez — APPROVED** [review]
/lgtm
/approve

**Comment by qinqon** [comment]
We have good results from https://github.com/kubevirt/kubevirtci/pull/557

**Pull request merged**
