### PR TITLE
Remove the 1.22 kubevirtci provider

### PR DESCRIPTION
**Pull request by brianmcarey**
Both the 1.25 and 1.26-rc providers have been added. Removing 1.22 as it is no longer needed or supported by kubevirtci.

Since the addition of the 1.26-rc provider the automated removal of unsupported providers is no longer working[1]

/cc @dhiller @xpivarc @oshoval 

[1] https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirtci-cluster-unsupported-version-remover/1600502013647392768#1:build-log.txt%3A149

Signed-off-by: Brian Carey <bcarey@redhat.com>

### CODE REVIEW

**Comment by oshoval** [comment]
Thanks
project-infra is free of 1.22 ?

**Review by oshoval — APPROVED** [review]

**Comment by brianmcarey** [comment]
> Thanks project-infra is free of 1.22 ?

I have removed the 1.22 lanes here - https://github.com/kubevirt/project-infra/pull/2506 and updated a couple of the special lanes here - https://github.com/kubevirt/project-infra/pull/2487

**Comment by oshoval** [comment]
Awesome, so according those also kind-1.22-sriov need to be removed please
Just please let Or Mergi and Orel Misan know about it

**Comment by brianmcarey** [comment]
> Just please let Or Mergi and Orel Misan know about it

I was going to do that as another PR with them as reviewers - it shouldn't stop the removal of this.

**Comment by oshoval** [comment]
> > Just please let Or Mergi and Orel Misan know about it
> 
> I was going to do that as another PR with them as reviewers - it shouldn't stop the removal of this.

Sure, already lgtmed, thanks

**Review by dhiller — APPROVED** [review]
/approve

Finally :)

**Comment by oshoval** [comment]
We can maybe cancel the post-submit of it, no need to create a provider for this PR
#920 will soon be merged and create the needed one

**Pull request merged**
