### PR TITLE
Improve err msg on cluster image pull

### PR DESCRIPTION
**Pull request by xpivarc**

### CODE REVIEW

**Comment by oshoval** [comment]
tried to run this locally,
but the error comes from the daemon maybe ?
`Error response from daemon: invalid reference format`
same print with and without, unless i missed something

note that it can easily simulated locally, so it might help to debug

**Comment by xpivarc** [comment]
> tried to run this locally, but the error comes from the daemon maybe ? `Error response from daemon: invalid reference format` same print with and without, unless i missed something
> 
> note that it can easily simulated locally, so it might help to debug

Yes, it comes from the daemon but the `gocli` is the client and therefore we should be able to decorate the err we get from it.
Weird that you don't see anything more than the error. This indicates it is a different command that is failing.

**Comment by oshoval** [comment]
https://github.com/kubevirt/kubevirtci/pull/1054
should fix the bug

**Review by brianmcarey — COMMENTED** [review]
I think this is still worth adding

/lgtm

**Review by brianmcarey — APPROVED** [review]
/approve

**Pull request merged**
