### PR TITLE
Update kubevirtci images to latest digest

### PR DESCRIPTION
**Pull request by danielBelenky**
The latest versions of the updated images feature a modified path for
the pre-provisioned test directory.

PR which updated the paths: https://github.com/kubevirt/kubevirtci/pull/436

Signed-off-by: Daniel Belenky <dbelenky@redhat.com>

### CODE REVIEW

**Comment by oshoval** [comment]
Please add in the PR description / commit description that it refer to 
https://github.com/kubevirt/kubevirtci/pull/436

**Comment by danielBelenky** [comment]
> Please add in the PR description / commit description that it refer to
> #436

done.

**Review by oshoval — APPROVED** [review]
I would suggest to add the ref in the commit message as well, but up to you
Thanks

**Comment by oshoval** [comment]
why you changed the 1.17 hash ?

**Comment by danielBelenky** [comment]
> why you rechanged the 1.17 hash ?
> (unless previous was a mistake)

because the previous one was incorrect...

**Review by oshoval — APPROVED** [review]
np
wanted to understand and make sure,
btw this is why posting the push jobs that were used is helpful sometimes.
Thanks

**Review by dhiller — COMMENTED** [review]
/lgtm
/approve

**Review by dhiller — APPROVED** [review]

**Pull request merged**
