### PR TITLE
Asking to be added as an approver

### PR DESCRIPTION
**Pull request by enp0s3**
Signed-off-by: Igor Bezukh <ibezukh@redhat.com>

### CODE REVIEW

**Review by fgimenez — COMMENTED** [review]
/lgtm

It would be good to have the owners alphabetically ordered, but not necessarily on this PR :+1:

**Review by dhiller — APPROVED** [review]
/approve
/hold

Ping me if you want to reorder, otherwise feel free to unhold.

**Comment by enp0s3** [comment]
@dhiller @fgimenez Let me fix the alphabet ordering in OWNERS, but I prefer to do it in a separate PR

**Pull request merged**
