### PR TITLE
centos9: Add --numa support to vm.sh

### PR DESCRIPTION
**Pull request by lyarwood**
**What this PR does / why we need it**:

This change adds basic support to the vm.sh script for defining a number of NUMA nodes per host with vCPUs and memory spread equally between them.

This change is broken out from the rest of the series wiring up gocli and cluster-up as it needs to be present in the current centos9 image to be testable in such a PR.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

See https://github.com/kubevirt/kubevirtci/pull/1171 for how this will be used.

**Checklist**

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by lyarwood** [comment]
/cc @vladikr 
/cc @brianmcarey 

Hey folks, would you mind taking a look at this review and the wider series in https://github.com/kubevirt/kubevirtci/pull/1171, any and all comments welcome!

**Review by 0xFelix — APPROVED** [review]
/lgtm

**Comment by vladikr** [comment]
It looks good for me as well. Thanks @lyarwood !
/lgtm

**Pull request merged**
