### PR TITLE
kind, vgpu: Bump vgpu kind to k8s-1.25

### PR DESCRIPTION
**Pull request by oshoval**
Since we don't use CPU manager on vgpu lane we can bump to k8s-1.25
and remove the cpu manager configuration due to
https://github.com/kubernetes-sigs/kind/issues/2999 (affects k8s-1.24+ with cpu manager)

Rename vgpu lane to reflect the k8s version bump.

Kubevirtci Infra: https://github.com/kubevirt/project-infra/pull/2653
Kubvirt infra: https://github.com/kubevirt/project-infra/pull/2654

### CODE REVIEW

**Comment by oshoval** [comment]
/test check-up-kind-1.23-sriov

lets see it didn't affect sriov (since a common file was changed)

**Comment by oshoval** [comment]
@vladikr @brianmcarey @dhiller @xpivarc 
can you please take a look ?

this allows bumping vgpu lane to k8s-1.25
tested on kubevirt (both sriov and vgpu)
created infra PR as well

**Comment by oshoval** [comment]
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirtci/979/check-up-kind-1.23-vgpu/1633477265524264960
fails because provider was renamed
tested under kubevirt with local hack
infra PR attached

**Review by brianmcarey — COMMENTED** [review]
/lgtm

**Comment by xpivarc** [comment]
/lgtm
@dhiller Can I borrow your approve?

**Comment by oshoval** [comment]
> Please note that the issues with kind 1.24+ could still occur w/o CPU manager see [kubernetes-sigs/kind#2999 (comment)](https://github.com/kubernetes-sigs/kind/issues/2999#issuecomment-1362493138).

Interesting

> On the the SRIOV take, it can down to be flaky, tests were failing from time to time due to the missing permissions to /dev/null. I suggest to run the GPU lanes with this PR changes on kubevirt/kubevirt few times (about 5) verifying that it's actually stable.

I ran at least 3 or so and it was stable, I believe that as long as we don't touch the /dev/null we are fine
(which can be other bug of selinux imo, as we had on vm based providers).

Note that SR-IOV was not affected by this PR, still has cpu manager and k8s-1.23

**Review by dhiller — COMMENTED** [review]
/approve

**Comment by oshoval** [comment]
Btw the lane of vpgu on kubevirtci is optional, this is why it was merged even that the old lane failed

**Pull request merged**
