### PR TITLE
certcreator/certsecret: fix misspell for sucessfully

### PR DESCRIPTION
**Pull request by zhouhao3**
Signed-off-by: Zhou Hao <zhouhao@fujitsu.com>

### CODE REVIEW

**Review by oshoval — APPROVED** [review]
Thanks

just keep in mind this file isn't used anymore
since the sriov operator isn't used

**Comment by oshoval** [comment]
please rebase

**Comment by zhouhao3** [comment]
Thanks, done.

**Comment by oshoval** [comment]
lanes are broken, not because of the PR of course

**Review by oshoval — APPROVED** [review]

**Pull request merged**
