### PR TITLE
Update centos stream version to 20240108.0 tag

### PR DESCRIPTION
**Pull request by brianmcarey**
From time to time old centos stream 9 images are removed and cleaned up,
this can cause publishes of kubevirtci[1] and presubmits to fail.

Updating to 20240108.0

[1] https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/publish-kubevirtci/1745004368974843904#1:build-log.txt%3A2263

### CODE REVIEW

**Comment by oshoval** [comment]
i think we should pin a version, we can create a bump helper / automation
otherwise we are too prone for bugs

**Comment by brianmcarey** [comment]
@oshoval in the interest of getting these lanes passing again - I have bumped the version to 20240108.0 and got rid of the change to latest.

**Review by oshoval — APPROVED** [review]
Thanks

**Review by dhiller — APPROVED** [review]
/approve

**Pull request merged**
