### PR TITLE
sriov, Fix certsecret logic in case of etcd timeout

### PR DESCRIPTION
**Pull request by oshoval**
In case `etcdserver: request timed out` error occurs during `secret` creation,
the `secret` might got created, and only the response was `etcdserver: request timed out`.
Current logic will Poll and fail repeatedly, ending with `already exists` error, 
even that the `secret` was actually created.

Therefore the changes are:
* First make sure the `secret` doesn't exists, in case it exists exit with error, 
as certsecret isn't meant to be execute twice, as it doesn't meant to create a `secret` twice.
* In case there is an error when creating the `secret`, exit with success in case the error is `AlreadyExists`,
because we know the `secret` didn't exist before we created it (see previous bullet).

Seen at:
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirtci/481/check-up-kind-1.17-sriov/1329459762047225856

```
2020/11/19 16:44:17 failed to create secret 'operator-webhook-service': etcdserver: request timed out
2020/11/19 16:44:26 failed to create secret 'operator-webhook-service': secrets "operator-webhook-service" already exists
```
Signed-off-by: Or Shoval <oshoval@redhat.com>

### CODE REVIEW

**Comment by qinqon** [comment]
/hold

We have to verify cluster-up sriov kind lane.

**Comment by oshoval** [comment]
@qinqon 
I tested and it passed, after that i just updated the commit message so didn't bother to retest.
I also tested it in several edge cases locally (injecting scenarios).
Please see that i ran the lane here
https://github.com/kubevirt/kubevirtci/pull/489#issuecomment-732272481
and that it passed here
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirtci/489/check-up-kind-1.17-sriov/1330911328662982656

**Comment by oshoval** [comment]
@qinqon 
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirtci/489/check-up-kind-1.17-sriov/1331132033195315200
Passed

/retest
For the other lanes upon your request.
Thanks

**Comment by oshoval** [comment]
Thanks Quique

**Pull request merged**
