### PR TITLE
Fix a race in the scp calls

### LINKED ISSUE #668: [Flaky CI] Sometimes deploying prometheus artifacts results with runtime error: `invalid memory address or nil pointer dereference`
For example this prow [lane](https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_cluster-network-addons-operator/955/pull-e2e-cluster-network-addons-operator-nmstate-functests/1432628512748998656#1:build-log.txt%3A558) failing on CNAO on [this line](https://github.com/kubevirt/cluster-network-addons-operator/blob/main/cluster/up.sh#L26):
```
$(cluster::path)/cluster-up/up.sh
```

logs when fails looks like this:
```
prometheusrule.monitoring.coreos.com/kube-prometheus-rules created
prometheusrule.monitoring.coreos.com/prometheus-operator-rules created
prometheusrule.monitoring.coreos.com/prometheus-k8s-prometheus-rules created
service/prometheus-nodeport created
service/grafana-nodeport created
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x9ab01c]
goroutine 22 [running]:
kubevirt.io/kubevirtci/cluster-provision/gocli/cmd.scp.func2(0xc000196900)
	/home/prow/go/src/github.com/kubevirt/kubevirtci/cluster-provision/gocli/cmd/scp.go:191 +0x5c
created by kubevirt.io/kubevirtci/cluster-provision/gocli/cmd.scp
	/home/prow/go/src/github.com/kubevirt/kubevirtci/cluster-provision/gocli/cmd/scp.go:189 +0xabc
Makefile:130: recipe for target 'cluster-up' failed
make: *** [cluster-up] Error 2
+ EXIT_VALUE=2
+ set +o xtrace
```

### PR DESCRIPTION
**Pull request by rmohr**
Ensure that io pipes are created before the ssh session is statred by
creating the pipes outside of the go routine wich runs in parallel to
the session.

Errors like

```bash
goroutine 22 [running]:
kubevirt.io/kubevirtci/cluster-provision/gocli/cmd.scp.func2(0xc000196900)
	/home/prow/go/src/github.com/kubevirt/kubevirtci/cluster-provision/gocli/cmd/scp.go:191 +0x5c
created by kubevirt.io/kubevirtci/cluster-provision/gocli/cmd.scp
	/home/prow/go/src/github.com/kubevirt/kubevirtci/cluster-provision/gocli/cmd/scp.go:189 +0xabc
```

are the symptom.

Fixes #668.

### CODE REVIEW

**Review by fgimenez — COMMENTED** [review]
/lgtm

great catch!

**Review by RamLavi — APPROVED** [review]
/lgtm

**Pull request merged**
