### PR TITLE
Fix Prometheus config

### PR DESCRIPTION
**Pull request by assafad**
**What this PR does / why we need it**:
Fix Prometheus configuration that was applied in https://github.com/kubevirt/kubevirtci/pull/1132 to select all prometheusrules, as their namespaces depend on the installation. Different repos create different namespaces (`kubevirt`, `kubevirt-hyperconverged`, etc).
**Checklist**

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

**Release note**:

```release-note
None
```

### CODE REVIEW

**Comment by machadovilaca** [comment]
looks good to me, but I think it would be a good initiative to have some kind of common rules for the created resources across components. This situation of some PrometheusRule resources having the `kubevirt.io` label and others not, is a good example.

**Comment by assafad** [comment]
> looks good to me, but I think it would be a good initiative to have some kind of common rules for the created resources across components. This situation of some PrometheusRule resources having the `kubevirt.io` label and others not, is a good example.
@machadovilaca It's not about PrometheusRules labels, it's about namespaces labels (`ruleNamespaceSelector`). Not all namespaces that are created with repositories `make cluster-sync` have the ``kubevirt.io` label.

**Review by brianmcarey — COMMENTED** [review]
This looks good to me - thanks @assafad ! 

@machadovilaca what do you think?

/approve

**Pull request merged**
