### PR TITLE
Revert "feat: Bumped calico cni version from v3.18.0 to v3.27.2 (#1281)"

### PR DESCRIPTION
**Pull request by brianmcarey**
**What this PR does / why we need it**:

This reverts commit d5c1f38a90dc0316e01545a32deaf63cce106223.

The bump kubevirtci PR is failing on the network e2e lanes. This looks to be related to this update of calico.

Reverting to unblock the bump PR and to verify that the network failures are related to this calico update.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

/cc @chandramerla @xpivarc 

**Checklist**

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by chandramerla** [comment]
Changes wise it looks good to me and you can go ahead merging based on your findings from tests. Thanks, @brianmcarey !

**Review by vamsikrishna-siddu — COMMENTED** [review]
Looks good to me
/lgtm

**Review by brianmcarey — COMMENTED** [review]
/hold cancel

/approve 

To unblock the bump-kubevirtci - PR to upgrade calico to v.1.25.2 to follow.

**Pull request merged**
