### PR TITLE
Adjust KCI for k8s-1.22 provider

### PR DESCRIPTION
**Pull request by enp0s3**
Adjust the configuration files and the scripts to meet the k8s 1.22 requirements

Signed-off-by: Igor Bezukh <ibezukh@redhat.com>

### CODE REVIEW

**Review by oshoval — COMMENTED** [review]
Nice, 
I remember something about EndpointSliceProxying that Quique worked with, might worth to run sig-network (unless already done), or verify with Quique that we are safe ?

**Comment by enp0s3** [comment]
@oshoval Hello! Thank you for the review. I would like to test the lanes on the CI infra rather than doing it locally. My plan is to get this code merged, then bump KCI in KV, and then I will create a temp. PR and will start testing the 1.22 lanes. Currently the 1.22 lanes are optional in our prow configuration files. 

Regarding the `EndpointSliceProxying` I've found the PR of @qinqon where he disabled it and IIUC the reason was that it's not stable. @qinqon please keep me honest here.

**Comment by oshoval** [comment]
> @oshoval Hello! Thank you for the review. I would like to test the lanes on the CI infra rather than doing it locally. My plan is to get this code merged, then bump KCI in KV, and then I will create a temp. PR and will start testing the 1.22 lanes. Currently the 1.22 lanes are optional in our prow configuration files.

I meant on CI, but np, since its a new lane, and not mandatory yet, it is fine to do in steps.

**Review by dhiller — APPROVED** [review]
/approve

Thanks for the fixes!

**Pull request merged**
