### PR TITLE
fix make cluster-up error when using kind-k8s-1.17

### PR DESCRIPTION
**Pull request by zhlhahaha**
set default value for KIND_VERSION, KIND_NODE_IMAGE and
KUBECTL_PATH in kind-k8s-1.17/provider.sh

### CODE REVIEW

**Comment by zhlhahaha** [comment]
Hi @oshoval @fgimenez
Would you mind taking a look when you have time, thanks.

**Review by oshoval — COMMENTED** [review]
Hi @zhlhahaha 
Thanks for the PR

Can you please use `set_kind_params`
as it exists on cluster-up/cluster/kind-k8s-sriov-1.17.0/provider.sh ?
simply by coping the function,
and calling this at the end:
(moved the source to the end as well)
```
set_kind_params

source ${KUBEVIRTCI_PATH}/cluster/kind/common.sh
```

Thanks

**Comment by zhlhahaha** [comment]
Thanks for your quick reply @oshoval 
> Can you please use set_kind_params

Is the purpose for this change to facilitating managing these parameters?

**Comment by oshoval** [comment]
> Thanks for your quick reply @oshoval
> 
> > Can you please use set_kind_params
> 
> Is the purpose for this change to facilitating managing these parameters?

Yes, and also that the 2 providers will be aligned as much as possible,
please see https://github.com/kubevirt/kubevirtci/pull/540
for the scope (i guess you already saw according the changes of the README.md)

**Review by oshoval — APPROVED** [review]
Thanks

**Comment by oshoval** [comment]
/cc @fgimenez 
can you take a look please?

the failure is not due to this PR, as it changes only the kind lane (even not the sriov-kind lane)

**Comment by oshoval** [comment]
@qinqon @fgimenez 
can you take a look please?
its totally safe, its not even a provider that we have CI for
(its the kind, non sriov one)

**Pull request merged**
