### PR TITLE
Fix ssh problem and OpenShift builds

### LINKED ISSUE #46: Provisioning of nodes sometime fails on ssh.sh command
One of examples:
```
+ make cluster-up
./cluster/up.sh
Downloading ...........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
Downloading ........................................................
Downloading ...................................................................................................................
/bin/bash: ssh.sh: command not found
provisioning node node02 failed
make: *** [cluster-up] Error 1
```

### PR DESCRIPTION
**Pull request by slintes**
Delete ssh_ready after provisioning, else it won't work for run command.
Also pin ansible version, version 2.7 doesn't work, see https://github.com/openshift/openshift-ansible/issues/10368

Uploading new images atm, will test them on a kubevirt PR in order to see if this really solved the issue.

Fixes #46

### CODE REVIEW

**Comment by rmohr** [comment]
@slintes YESSS! Finally! :+1:

**Comment by slintes** [comment]
I'm blocked by failing Openshift provisioning, the api pod doesn't start (also on older commit)... investigating

**Comment by slintes** [comment]
This is crazy: first the openshift images didn't build because of a too new Ansible version inside the image, and now it seems I can't build the os-crio image, probably because of a too new docker version on my machine (https://github.com/moby/moby/issues/37581)... downgrading docker now

**Comment by slintes** [comment]
finally all images pushed. Let's see if they work:
https://github.com/kubevirt/kubevirt/pull/1624

**Comment by cynepco3hahue** [comment]
Good catch, I forgot that we also use `ssh.sh` script on reprovision phase.

**Comment by slintes** [comment]
also on 2nd test run no ssh.sh issues anymore, only some "usual" test failures

/hold cancel

**Pull request merged**
