### PR TITLE
Bump default provider version

### PR DESCRIPTION
**Pull request by xpivarc**

### CODE REVIEW

**Review by brianmcarey — COMMENTED** [review]
It could be good to bump it in the documentation too - https://github.com/kubevirt/kubevirtci/blob/8cca8c0d22796f2a99dc2faf2f6f3bc911501a9a/KUBEVIRTCI_LOCAL_TESTING.md?plain=1#L38

https://github.com/kubevirt/kubevirtci/blob/8cca8c0d22796f2a99dc2faf2f6f3bc911501a9a/KUBEVIRTCI_LOCAL_TESTING.md?plain=1#L19

**Review by dhiller — APPROVED** [review]
/approve

**Comment by xpivarc** [comment]
@dhiller @brianmcarey Maybe we can also remove the 1.22 check?

**Comment by dhiller** [comment]
> @dhiller @brianmcarey Maybe we can also remove the 1.22 check?

While the provider is still there we might just make it optional?

**Pull request merged**
