### PR TITLE
istio, Add assertion that istio deployment succeeded

### PR DESCRIPTION
**Pull request by oshoval**
In case istio is deployed, it waits for the deployment
to complete.
There was a missing assertion in case it didn't
complete successfully.

Signed-off-by: Or Shoval <oshoval@redhat.com>

### CODE REVIEW

**Comment by oshoval** [comment]
Failure is not due to the PR
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirtci/633/check-provision-k8s-1.20/1409430942715482112

its due to kubevirt deployment timeout

**Comment by oshoval** [comment]
something is weird here
closing for now

**Comment by oshoval** [comment]
problem is not due to this PR, will continue once its fixed

**Comment by oshoval** [comment]
`+ dnf install -y kernel-modules-4.18.0-315.el8.x86_64`
fails

lets try again and see if it just transient
/test check-provision-k8s-1.19

**Review by ormergi — APPROVED** [review]

**Comment by oshoval** [comment]
Thanks Or
@qinqon can you take a look please?

**Pull request merged**
