### PR TITLE
Remove kind-1.22-sriov provider as no longer needed

### PR DESCRIPTION
**Pull request by brianmcarey**
The kind-1.23-sriov provider has been introduced and is already looking stable in kubevirt testing[1]

There is no need for the kind-1.22-sriov provider as the lanes that were using it have been removed[2]

[1] https://testgrid.k8s.io/kubevirt-periodics#periodic-kubevirt-e2e-k8s-1.23-sriov [2] https://github.com/kubevirt/project-infra/pull/2506

/cc @orelmisan @ormergi @EdDev 

Signed-off-by: Brian Carey <bcarey@redhat.com>

### CODE REVIEW

**Review by EdDev — APPROVED** [review]
Thank you!

@ormergi , can you have a look and see nothing is missed?

**Review by orelmisan — APPROVED** [review]
Thank you @brianmcarey

**Review by ormergi — APPROVED** [review]

**Pull request merged**
