### PR TITLE
kubevirt-testing is no longer needed

### PR DESCRIPTION
**Pull request by rmohr**
kubevirt/kubevirt is creating now the necessary images via bazel based on https://github.com/kubevirt/kubevirt/pull/4710.

### CODE REVIEW

**Review by fgimenez — APPROVED** [review]
/lgtm

I guess https://github.com/kubevirt/kubevirtci/pull/406 is no longer needed, right?

**Comment by rmohr** [comment]
> I guess #406 is no longer needed, right?

right. :+1:

**Comment by rmohr** [comment]
/close

In the meantime another container sneaked in. That needs to be addressed first.

**Pull request closed without merging**
