### PR TITLE
Re-push k8s-1.17 provider

### PR DESCRIPTION
**Pull request by dhiller**

### CODE REVIEW

**Comment by dhiller** [comment]
check-provision-k8s-1.17

**Comment by jean-edouard** [comment]
Tried `8207701620b4e51e2671d4e90436d9823a0099a1270b4668a4e24a32efb5f4b3`, still getting that infamous `Error response from daemon: client version 1.40 is too new. Maximum supported API version is 1.39` :(

**Comment by dhiller** [comment]
Obsolete.

**Pull request closed without merging**
