### PR TITLE
Added os-3.11.0-multus-sriov provider

### PR DESCRIPTION
**Pull request by booxter**
This provider is based on regular os-3.11-multus provider. It deploys SR-IOV
components (CNI, DP with config file, sriov network attachment) on top.

Note that when deploying from this image, to make SR-IOV device plugin to
allocate VFs from PFs available on the node, one should list PF addresses in
/etc/pcidp/config.json and then restart sriov device plugin pods.

### CODE REVIEW

**Comment by booxter** [comment]
@rmohr assuming we get this PR approved, we'll need to push a new image to dockerhub. How do I get access to it? I was told you shared permissions with Sebastian in the past.

**Comment by booxter** [comment]
@phoracek do you have a link handy to ConfigMap adoption for DP configuration purposes? I think I'll need to adopt the same here in manifests carried with the CI repo.

**Comment by phoracek** [comment]
@booxter sure https://github.com/kubevirt/kubevirt-ansible/pull/539

**Comment by booxter** [comment]
/hold

This new 'driver' may not be useful for stdci after all since we need bare metal access to the node PFs to make it work, and a driver implies having another layer of virtualization (qemu inside a node image) that we would need to pass PFs through, which is not obvious how to achieve.

Marcin is exploring using 'local' provider instead. In the meantime, I am going to hold off this patch not to introduce images that are not used anywhere.

**Pull request closed without merging**
