### PR TITLE
Revert "Bump github.com/containerd/containerd in /cluster-provision/gocli"

### PR DESCRIPTION
**Pull request by brianmcarey**
This reverts commit 32ab159e851e86b0bc8410d1251748da78250992.

/cc none

### CODE REVIEW

**Comment by dhiller** [comment]
@brianmcarey is this PR already good to review? The tests don't look that good?

**Comment by brianmcarey** [comment]
/lgtm

/override check-provision-k8s-1.27

The bump-kubevirtci PR has been broken since this change went in[1]. the check-provision-k8s-1.27 lane is hitting an issue cleaning up the test namespaces - this can be investigated separately. 

[1] https://github.com/kubevirt/kubevirt/pull/9616

**Comment by brianmcarey** [comment]
@dhiller can you add an lgtm here? we need to try to get kubevirtci back to a good state.

**Comment by oshoval** [comment]
do we want this back ? or it also did problems by its own ?

**Comment by brianmcarey** [comment]
> do we want this back ? or it also did problems by its own ?

Dependabot created another PR for this here - https://github.com/kubevirt/kubevirtci/pull/1003 - lets see how the CI lanes go.

**Pull request merged**
