### PR TITLE
cnao: Fix bump script

### PR DESCRIPTION
**Pull request by oshoval**
**What this PR does / why we need it**:
Adapt script due to the reafactor.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Checklist**

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by oshoval** [comment]
@brianmcarey 
hi, can you please take a look ?

i can either make it ready, or also bump in the same PR soon a new release, whatever you prefer
split or unite
thanks

**Comment by brianmcarey** [comment]
> @brianmcarey hi, can you please take a look ?
> 
> i can either make it ready, or also bump in the same PR soon a new release, whatever you prefer split or unite thanks

Hi @oshoval - i took a quick look. I am not sure what you are trying to do? The CNAO manifests now live under gocli/opts/cnao/manifests ?

**Comment by oshoval** [comment]
> > @brianmcarey hi, can you please take a look ?
> > i can either make it ready, or also bump in the same PR soon a new release, whatever you prefer split or unite thanks
> 
> Hi @oshoval - i took a quick look. I am not sure what you are trying to do? The CNAO manifests now live under gocli/opts/cnao/manifests ?

Hi Brian, thanks
the script was broken so tried to fix it 

ah hmm
there are on both paths
worth indeed first to understand each

./cluster-provision/gocli/opts/cnao/manifests/network-addons-config.crd.yaml
./cluster-provision/k8s/1.29/manifests/cnao/network-addons-config.crd.yaml
./cluster-provision/k8s/1.30/manifests/cnao/network-addons-config.crd.yaml
./cluster-provision/k8s/1.31/manifests/cnao/network-addons-config.crd.yaml


iirc @aerosouund said he plan to fix it on a follow-up

**Comment by oshoval** [comment]
according https://github.com/kubevirt/kubevirtci/pull/1262
the only file that matters in a PR is `./cluster-provision/gocli/opts/cnao/manifests/network-addons-config.crd.yaml` iiuc
if so worth to delete the others

```
/cluster-provision/k8s/1.29/manifests/cnao/network-addons-config.crd.yaml
./cluster-provision/k8s/1.30/manifests/cnao/network-addons-config.crd.yaml
./cluster-provision/k8s/1.31/manifests/cnao/network-addons-config.crd.yaml
```

will adapt the PR accordingly to just bump `./cluster-provision/gocli/opts/cnao/manifests/network-addons-config.crd.yaml`

@aerosouund wdyt?

**Comment by oshoval** [comment]
adapted the script, had to rename the crd file to the original file
(didnt test provision works with that)

/test check-provision-k8s-1.31

**Comment by oshoval** [comment]
/test check-provision-k8s-1.31

i dont like the current code, lets see if it pass first

**Comment by aerosouund** [comment]
@oshoval it will fail again. let me explain why

the part that applies the kubernetes resources walks the file tree alphabetically

```golang
	err := fs.WalkDir(f, "manifests", func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if !d.IsDir() && filepath.Ext(path) == ".yaml" {
			yamlData, err := f.ReadFile(path)
			if err != nil {
				return err
			}
			yamlDocs := bytes.Split(yamlData, []byte("---\n"))
			for _, yamlDoc := range yamlDocs {
				if len(yamlDoc) == 0 {
					continue
				}
```
this is why the name `network-addons-config.crd.yaml` was changed to `crd.yaml`, so that it comes up at an earlier alphabetical order and hence gets applied before the custom resource itself

the original approach i had in mind was to specify manifests by their name during apply but we since changed it to avoid having to hardcode names.
we had this same problem in rook ceph and we solved it by appending a 0 to the filenames we wanted applied first. we can follow this here as well, or manually specify that we want the custom resource definition to be applied first

**Comment by oshoval** [comment]
thanks, latest version here doesnt rename
i think " specify that we want the custom resource definition to be applied first" will be good, while keeping the original name

what about deleting old files
we can right ?
```
/cluster-provision/k8s/1.29/manifests/cnao/network-addons-config.crd.yaml
./cluster-provision/k8s/1.30/manifests/cnao/network-addons-config.crd.yaml
./cluster-provision/k8s/1.31/manifests/cnao/network-addons-config.crd.yaml
```

**Comment by aerosouund** [comment]
> i think " specify that we want the custom resource definition to be applied first" will be good, while keeping the original name

Yeah, this can be indeed achieved

> what about deleting old files
> we can right ?

Yeah they aren't being used anymore

**Comment by oshoval** [comment]
> Yeah, this can be indeed achieved

Would you like to do that once you have time please ?
if so i will just close this PR
thanks

**Comment by aerosouund** [comment]
@oshoval 
By when will you need this ?

**Comment by oshoval** [comment]
> @oshoval By when will you need this ?

no rush atm, it just be nice to have
thanks, since even when this PR is closed i can use it for bumping cnao (that i will do soon)

**Pull request closed without merging**
