### PR TITLE
Align the cri-o version v1.28.0 with kubernetes version

### PR DESCRIPTION
**Pull request by brianmcarey**
Use the mirror of the new cri-o repos[1] for v1.28

[1] https://kubernetes.io/blog/2023/10/10/cri-o-community-package-infrastructure/

### CODE REVIEW

**Comment by brianmcarey** [comment]
The latest 1.28 release of cri-o has broken the migration conformance tests. 

It looks like we depend on the Image ID including the image digest[1] when creating the migration template which is no longer the case with the latest crio[2]. 

`{"component":"virt-controller","level":"info","msg":"reenqueuing Migration kubevirt-test-default1/test-migration-xpb7q","pos":"migration.go:233","reason":"failed to render launch manifest: can not proceed with the migration when no reproducible image digest can be detected: failed to identify image digest for container \"registry:5000/kubevirt/alpine-with-test-tooling-container-disk:devel\" with id \"8aba57ea67e3518f3b7fcbf32954bd2c0bd60d46ed55672a0fcec66076d4a6d4\"","timestamp":"2023-10-23T15:22:33.398815Z"}`

I ran the sig-compute-migrations suite against the new published provider and this results in the majority of tests failing. 


[1] https://github.com/kubevirt/kubevirt/blob/40b219b37714475a998c2cfd6129b9635400502a/pkg/container-disk/container-disk.go#L443
[2] https://github.com/cri-o/cri-o/pull/7149

**Comment by brianmcarey** [comment]
the check-provision lane for v1.28 is now passing with the updated version of cri-o since https://github.com/kubevirt/kubevirt/pull/10747 was merged.

**Review by dhiller — APPROVED** [review]
/approve

**Pull request merged**
