### PR TITLE
cluster-up, cnao: Do not deploy OVS-CNI

### PR DESCRIPTION
**Pull request by ormergi**
**What this PR does / why we need it**:
There is no actual need to deploy OVS-CNI dy default at the moment, we dont test OVS CNI e2e in kubevirt/kubevirt.

Also the ephemeral cluster nodes does not have OVS back-end installed causing OVS-CNI pods to get into crush-loop all over CI.

In case OVS-CNI is required in certain environments, it can be deployed by patching the existing cluster-network-addons instance.

Set CNAO to not deploy OVS-CNI pods and reduce some memory consumption.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
Other kubevirt org repositories that use kubevirt/kubevirtci for test/dev environment could patch CNAO NetworkAddonsConfig CR (NAC) and add the necessary components.
Alternatively, set the environment variable `KUBVIRT_WITH_CNAO_SKIP_CONFIG=true` and deploy new NAC with all components that are necessary

**Checklist**

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

**Release note**:

```release-note
cluster-up: CNAO does not deploy OVS-CNI by default
```

### CODE REVIEW

**Comment by ormergi** [comment]
Rebasesd

**Review by brianmcarey — APPROVED** [review]
/lgtm

/approve

thanks @ormergi !

**Comment by oshoval** [comment]
Added it to the bump script so this change wont be overridden upon bumping
https://github.com/kubevirt/kubevirtci/pull/1215/files#diff-a62a4a90160c0961988d25e478dc85642e5404173a3151b42afd8777e90308d1R61
thx

**Pull request merged**
