### PR TITLE
update kube-calico from beta api to stable v1

### PR DESCRIPTION
**Pull request by ashleyschuett**
Signed-off-by: Ashley Schuett <aschuett@redhat.com>

### CODE REVIEW

**Comment by dhiller** [comment]
Not sure whether these are flakes resp. timing issues or real problems, i suspect the former.

/retest

**Review by dhiller — APPROVED** [review]
Looks like a straight forward update to me, @qinqon WDYT?

**Comment by dhiller** [comment]
Hm, looks like the calico setup needs more time somehow. @ashleyschuett mind taking a look there? Maybe we can just increase some wait time on the pods (not familiar with the calico setup at all TBH)

**Comment by ashleyschuett** [comment]
yup, looking into! seems I broke something.

**Comment by ormergi** [comment]
Hey @ashleyschuett could you please elaborate the source of the new manifest?

**Comment by ashleyschuett** [comment]
@ormergi thanks for the review and comment! I have updated as you specified however I am not sure how to push the image to the quay.io/kubevirtci/* repos. I don't have permissions but maybe there is some script or tool I'm suppose to use?

**Comment by dhiller** [comment]
> @ormergi thanks for the review and comment! I have updated as you specified however I am not sure how to push the image to the quay.io/kubevirtci/* repos. I don't have permissions but maybe there is some script or tool I'm suppose to use?

@ashleyschuett I can assist in creating a repo if none does exist. I'd suggest creating a new folder under `cluster-provision` directory for this and store the Dockerfile (and related files) there. Give me the details, then I'll create one and give you access to it. (Sorry, we haven't yet automated pushing those images yet)

**Comment by ormergi** [comment]
@ashleyschuett  @dhiller Hey we did it for other images we used to pull from docker hub
@fgimenez Could you help up us with mirror calico's image?

**Comment by fgimenez** [comment]
> @fgimenez Could you help up us with mirror calico's image?

Done, these images are now available, mirrored from dockerhub:
* quay.io/kubevirtci/calico_cni:v3.19.1
* quay.io/kubevirtci/calico_kube-controllers:v3.19.1
* quay.io/kubevirtci/calico_node:v3.19.1
* quay.io/kubevirtci/calico_pod2daemon-flexvol:v3.19.1

**Comment by dhiller** [comment]
> > @fgimenez Could you help up us with mirror calico's image?
> 
> Done, these images are now available, mirrored from dockerhub:
> 
>     * quay.io/kubevirtci/calico_cni:v3.19.1
> 
>     * quay.io/kubevirtci/calico_kube-controllers:v3.19.1
> 
>     * quay.io/kubevirtci/calico_node:v3.19.1
> 
>     * quay.io/kubevirtci/calico_pod2daemon-flexvol:v3.19.1

Is this automated or are we doing this on demand?

**Comment by ormergi** [comment]
@ashleyschuett looks good, could you please check this PR changes on kubevirt/kubevirt SRIOV lane before we merging this?

**Comment by fgimenez** [comment]
> Is this automated or are we doing this on demand?

on demand atm, we have a ticket for automating it

**Comment by ashleyschuett** [comment]
@ormergi  I have updated kubevirt/kubevirt PR https://github.com/kubevirt/kubevirt/pull/6048 to run with these changes to test SRIOV

**Comment by ashleyschuett** [comment]
@fgimenez I think something went wrong when pushing the `quay.io/kubevirtci/calico_cni:v3.19.1` image. Testing locally the `calico-node-*` pods come up when I use the `calico/cni:v3.19.1` image but the crashloop on the `install-cni` initContainer when I use `quay.io/kubevirtci/calico_cni:v3.19.1`

would you be able to redo the mirroring of this image?

**Comment by fgimenez** [comment]
> @fgimenez I think something went wrong when pushing the `quay.io/kubevirtci/calico_cni:v3.19.1` image

Sorry for the late response, I've repushed the image, let me know if you find any issue.

**Comment by ashleyschuett** [comment]
Finally figured it out what was going wrong. It's all good now!

**Comment by ashleyschuett** [comment]
/hold 

@ormergi is working on removing our dependency on calico

**Comment by enp0s3** [comment]
@ashleyschuett Hi. https://github.com/kubevirt/kubevirtci/pull/640 is merged

**Comment by rmohr** [comment]
> @ormergi is working on removing our dependency on calico

Is this related just to kind  or to all providers?

**Comment by ormergi** [comment]
> > @ormergi is working on removing our dependency on calico
> 
> Is this related just to kind or to all providers?

Just for kind

**Comment by ashleyschuett** [comment]
closing due to https://github.com/kubevirt/kubevirtci/pull/644

**Pull request closed without merging**
