### PR TITLE
Remove kind-1.23 provider as no longer required

### LINKED ISSUE #1087: Remove kind-1.23
Currently, the latest K8s stable release is 1.28.
KubeVirt supports the latest three K8s versions, meaning 1.28, 1.27 and 1.26.
K8s 1.23 is older than that, so this provider should be removed.

### PR DESCRIPTION
**Pull request by brianmcarey**
KubeVirt supports the latest three Kubernetes versions (currently 1.26,1.27 & 1.28) so the kind-1.23 is no longer required and should be removed. 

/cc @orelmisan @dhiller 

Closes #1087

### CODE REVIEW

**Review by orelmisan — COMMENTED** [review]
Are there any references to this provider under kubevirt/project-infra?

**Comment by brianmcarey** [comment]
> Are there any references to this provider under kubevirt/project-infra?

It was previously used by the arm e2e presubmit lane but that has been upgraded to kind-1.27
https://github.com/kubevirt/project-infra/blob/399654b1f22d24c9ebad6c537716d8aeba58db38/github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml#L1000

**Review by orelmisan — APPROVED** [review]
Thank you @brianmcarey

**Review by brianmcarey — COMMENTED** [review]
/approve

**Pull request merged**
