### PR TITLE
Revert "bump, cnao: k8s-1.2[4,5] to cnao v0.82.0 (#910)"

### PR DESCRIPTION
**Pull request by ormergi**
This reverts commit https://github.com/kubevirt/kubevirtci/commit/d73b264d09be4d1201541f449a4e05654e05334f https://github.com/kubevirt/kubevirtci/pull/910 due to similar reasons as https://github.com/kubevirt/kubevirtci/pull/904

PR https://github.com/kubevirt/kubevirt/pull/8864
Failing job example https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/8864/pull-kubevirt-e2e-k8s-1.25-sig-network/1599010914533642240

Signed-off-by: Or Mergi <ormergi@redhat.com>

### CODE REVIEW

**Comment by ormergi** [comment]
@dhiller could you please take a look?

**Review by brianmcarey — APPROVED** [review]
/approve

**Comment by brianmcarey** [comment]
/override check-up-kind-1.23-vgpu

Flaky test not related to the change

**Pull request merged**
