### PR TITLE
Updated  KUBEVIRT_PROVIDER env var default to k8s-1.17.0

### PR DESCRIPTION
**Pull request by eranco74**
Updated README.md to reflect that the default KUBEVIRT_PROVIDER is k8s-1.17.0 instead of k8s-1.13.3

### CODE REVIEW

**Comment by qinqon** [comment]
/hold

@eranco74 we have to fix first the issue with flannel vs calico I suppose.

**Comment by dhiller** [comment]
> /hold
> 
> @eranco74 we have to fix first the issue with flannel vs calico I suppose, #256

@eranco74 in the meantime you could just use k8s-1.16.2, which is working fine.

**Comment by eranco74** [comment]
> > /hold
> > @eranco74 we have to fix first the issue with flannel vs calico I suppose, #256
> 
> @eranco74 in the meantime you could just use k8s-1.16.2, which is working fine.

Thx

**Comment by eranco74** [comment]
#256 was merged
/test check-provision-k8s-1.17.0

**Comment by eranco74** [comment]
@qinqon , @dhiller  please approve

**Comment by qinqon** [comment]
@eranco74, we are still fixing issues with 1.17, please follow @dhiller suggestion.

**Pull request closed without merging**
