### PR TITLE
KubevirtCI rewrite draft

### PR DESCRIPTION
**Pull request by aerosouund**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**

https://github.com/kubevirt/kubevirtci/issues/1185

**Checklist**

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [x] PR: The PR description is expressive enough and will help future contributors
- [x] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [x] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

### CODE REVIEW

**Comment by dhiller** [comment]
/uncc
/cc @alicefr @xpivarc 

Since you folks were pinged on the issue, I suspect you have been talking to @aerosouund .

**Comment by dhiller** [comment]
> Thanks for your pull request. Before we can look at it, you'll need to add a 'DCO signoff' to your commits.
> 
> 📝 **Please follow instructions in the [contributing guide](https://github.com/kubevirt/kubevirtci/blob/master/CONTRIBUTING.md?rgh-link-date=2024-05-25T10%3A42%3A43Z) to update your commits with the DCO**
> 
> Full details of the Developer Certificate of Origin can be found at [developercertificate.org](https://developercertificate.org/).
> 
> **The list of commits missing DCO signoff**:
> 
> * [c907392](https://github.com/kubevirt/kubevirtci/commits/c907392dcfe31d6df8d7ac3f281cd86372b0dcef) Network ([Fix argument passing to qemu process #1](https://github.com/kubevirt/kubevirtci/pull/1))
> * [3c11b47](https://github.com/kubevirt/kubevirtci/commits/3c11b47134ff1285b3802807e263bab806b4bc77) ignore vendor
> * [18c3a41](https://github.com/kubevirt/kubevirtci/commits/18c3a416ca0ce84a78c430f02b3eba8b43fc4c74) ignore vendor
> * [f4f7e83](https://github.com/kubevirt/kubevirtci/commits/f4f7e8308567be27eab26f7371708535f7efd328) dont diff vendor
> * [469d3ff](https://github.com/kubevirt/kubevirtci/commits/469d3ff66ba8f5b2807ba0bee595e5a76c98f899) delete vendor directory
> * [35aaeaa](https://github.com/kubevirt/kubevirtci/commits/35aaeaac4f5a6024cc011d89755c606133b1a703) add vendor dir
> * [b57a472](https://github.com/kubevirt/kubevirtci/commits/b57a472923a6e8fa0e208ad01bb9b2add9285137) no changes to vendor

@aerosouund we only accept signed commits. You need to rework [each of the commits to have proper signing](https://github.com/kubevirt/kubevirt/blob/ddb0d2375c32a91412e3c4d6af9eada7b19c664b/CONTRIBUTING.md?plain=1#L78).

**Comment by alicefr** [comment]
@aerosouund on top of what Daniel said, please try to split the code in clean separate commits with some explanation. Even if this is a draft, it is, otherwise, difficult to review and understanding what you are doing.

**Comment by aerosouund** [comment]
@dhiller 
Of course, i am just keeping this as a pull request where you guys can just see the code. eventually i will clean up everything properly
@alicefr 
will do

**Pull request closed without merging**
