### PR TITLE
Deploy rook ceph toolbox alongside ceph

### PR DESCRIPTION
**Pull request by maya-r**
Requested by @mhenriks in [this PR to kubevirt](https://github.com/kubevirt/kubevirt/pull/5622#issuecomment-840583162).

### CODE REVIEW

**Review by dhiller — COMMENTED** [review]
/approve
/retest

**Review by dhiller — APPROVED** [review]

**Comment by dhiller** [comment]
Hrm, two test pods are stuck in pending here, maybe due to cluster load.

**Comment by mhenriks** [comment]
@maya-r I forgot a very important part of this:  can you use `rook/ceph:v1.5.8` instead `rook/ceph:master` in the manifests?  If not, pull a versioned image (not master) in provision.sh for all versions like here:   https://github.com/kubevirt/kubevirtci/blob/master/cluster-provision/k8s/1.17/provision.sh#L348-L356

**Comment by maya-r** [comment]
do I need to do anything to get a tag with this commit included?

**Comment by maya-r** [comment]
Looks like the [publish job for the commit](https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/publish-kubevirtci/1396451043532869632) failed.

**Pull request merged**
