### PR TITLE
Update vm-image-builder image URLs to Fedora 38

### PR DESCRIPTION
**Pull request by brianmcarey**
/cc @ormergi @xpivarc

### CODE REVIEW

**Comment by ormergi** [comment]
Is it possible to test it against kubevirt/kubevirt main, so that we get full feedback from all sigs gating jobs?

**Comment by brianmcarey** [comment]
> Is it possible to test it against kubevirt/kubevirt main, so that we get full feedback from all sigs gating jobs?

/hold

As @ormergi mentioned - it would be good to try to test this against kubevirt/kubevirt first.

**Comment by brianmcarey** [comment]
@ormergi looks like there is an issue with some of the network tests:

https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/9997/pull-kubevirt-e2e-k8s-1.27-sig-network/1674075699322818560

storage & compute look ok.

**Comment by brianmcarey** [comment]
> > @ormergi looks like there is an issue with some of the network tests:
> > https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/9997/pull-kubevirt-e2e-k8s-1.27-sig-network/1674075699322818560
> 
> Seems all issues there are related to IPv6?

Yes @ormergi suspects there is an issue with the new version of cloud-init - https://github.com/kubevirt/kubevirt/pull/9997#issuecomment-1613220799 - I haven't had a chance to revisit it yet.

**Comment by brianmcarey** [comment]
/close 

Fedora 39 is out now. Will try and update with that instead.

**Pull request closed without merging**
