### PR TITLE
Configure KinD clusters to use CI registry proxy (vGPU lane)

### PR DESCRIPTION
**Pull request by EdDev**
This is a complement to the registry proxy added to the SR-IOV lane [3].

As part of KinD clusters cluster up some images are pulled
directly for upstream registries instead of being cached and
pulled from the CI registry-proxy [1].

With this commit changes the underlying container-runtime
of each node will be configured to pull images from the
CI registry-proxy, according to the registry-proxy docs [2]

[1] https://github.com/kubevirt/project-infra/blob/cd344f77fdd0aa961ae190fd13787eae783aef01/github/ci/prow-deploy/kustom/components/docker-mirror-proxy/base/resources/deployment.yaml#L23
[2] https://github.com/rpardini/docker-registry-proxy#kind-cluster
[3] https://github.com/kubevirt/kubevirtci/pull/772

### CODE REVIEW

**Review by ormergi — APPROVED** [review]
From what I saw the vgpu provider does not deploy workloads that require caching,
this is why I didnt took care of it at #772.
Nevertheless this cant hurt and actually makes kubevirtci providers more consistent,
thanks for addressing this :slightly_smiling_face:

**Comment by EdDev** [comment]
Tested on kubevirt/kubevirt: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/7524/pull-kubevirt-e2e-kind-1.23-vgpu/1511776804837265408

**Comment by ormergi** [comment]
Configuring the proxy works https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/7524/pull-kubevirt-e2e-kind-1.23-vgpu/1511776804837265408#1:build-log.txt%3A618

/lgtm

**Pull request merged**
