### PR TITLE
Add second sound card

### PR DESCRIPTION
**Pull request by alicefr**
An additional sound cards can cover more advanced testing of the KubeVirt device plugin.

Signed-off-by: Alice Frosi <afrosi@redhat.com>

### CODE REVIEW

**Comment by alicefr** [comment]
fyi @vladikr

**Comment by vladikr** [comment]
Great, thanks @alicefr !
/approve

**Comment by vladikr** [comment]
@jean-edouard can you please take a look as well?

**Review by jean-edouard — APPROVED** [review]

**Pull request merged**
