### PR TITLE
Bump minor version of 1.24-ipv6 & 1.24-psa providers

### PR DESCRIPTION
**Pull request by brianmcarey**
This should be handled by the automated PR[1] but it is currently missed.

Bumping the minor version of the 1.24 provider variants.

[1] https://github.com/kubevirt/kubevirtci/pull/877

Signed-off-by: Brian Carey <bcarey@redhat.com>

### CODE REVIEW

**Review by oshoval — APPROVED** [review]
Thanks
Indeed it is missing by the automation
Not sure we need to bother doing it manually in the future until it is fixed as part of the automation

**Comment by brianmcarey** [comment]
> Thanks Indeed it is missing by the automation Not sure we need to bother doing it manually in the future until it is fixed as part of the automation

I will create an issue for the automation fix.

**Review by dhiller — APPROVED** [review]
/approve

**Comment by oshoval** [comment]
is there a 1.24-psa presubmit lane ? even manual one ?

**Comment by xpivarc** [comment]
> is there a 1.24-psa presubmit lane ? even manual one ?

Yes, there is.

**Comment by xpivarc** [comment]
> /test check-provision-k8s-1.24-psa

Unfortunately, this will not work afaik.

**Comment by oshoval** [comment]
> > /test check-provision-k8s-1.24-psa
> 
> Unfortunately, this will not work afaik.

It fails with sonobuoy, lets just skip sonobuoy on it then ?
we might want to make it always run, especially without sonobuoy, else if it fails it will fail the publish
but we can be brave and just fix in case there are problems

**Pull request merged**
