### PR TITLE
Remove ocp/okd cluster-up

### PR DESCRIPTION
**Pull request by qinqon**
They are not going to be maintained and current images are not working

Signed-off-by: Quique Llorente <ellorent@redhat.com>

### CODE REVIEW

**Comment by rmohr** [comment]
/lgtm
/hold

Can we get a PR which removes the corresponding jobs?

**Comment by qinqon** [comment]
@rmohr https://github.com/kubevirt/project-infra/pull/547

**Comment by oshoval** [comment]
> @rmohr: No jobs can be run with `/test all`.
> The following commands are available to trigger jobs:
> 
> * `/test check-provision-os-3.11.0`
> * `/test push-os-3.11.0`
> * `/test check-provision-os-3.11.0-crio`
> * `/test push-os-3.11.0-crio`
> * `/test check-provision-os-3.11.0-multus`
> * `/test push-os-3.11.0-multus`
> * `/test check-provision-okd-4.1`
> * `/test push-okd-4.1`
> * `/test check-up-okd-4.1`
> * `/test check-up-kind-k8s-1.17.0-ipv6`
> * `/test check-up-kind-k8s-1.14.2`
> * `/test check-up-kind-1.17-sriov`
> * `/test check-provision-okd-network-4.1`
> * `/test push-okd-network-4.1`
> * `/test check-up-okd-network-4.1`
> * `/test check-provision-okd-4.2`
> * `/test push-okd-4.2`
> * `/test check-up-okd-4.2`
> * `/test check-provision-ocp-4.3`
> * `/test push-ocp-4.3`
> * `/test check-up-ocp-4.3`
> * `/test check-provision-ocp-4.4`
> * `/test push-ocp-4.4`
> * `/test check-up-ocp-4.4`
> * `/test check-provision-ocp-cnao-4.4`
> * `/test push-ocp-cnao-4.4`
> * `/test check-up-ocp-cnao-4.4`
> * `/test check-provision-okd-4.3`
> * `/test push-okd-4.3`
> * `/test check-provision-k8s-1.15`
> * `/test push-k8s-1.15`
> * `/test check-provision-k8s-fedora-1.17.0`
> * `/test push-k8s-fedora-1.17.0`
> * `/test check-provision-k8s-1.18`
> * `/test push-k8s-1.18`
> * `/test check-provision-k8s-1.17`
> * `/test push-k8s-1.17`
> * `/test check-provision-k8s-1.16`
> * `/test push-k8s-1.16`
> * `/test check-provision-k8s-1.14`
> * `/test push-k8s-1.14`
> * `/test check-gocli`
> * `/test push-gocli`
> * `/test check-base`
> * `/test push-base`
> * `/test check-centos7`
> * `/test push-centos7`
> * `/test check-centos8`
> * `/test push-centos8`
> * `/test check-fedora`
> * `/test push-fedora`

this list should be updated as well please if possible

**Comment by rmohr** [comment]
/test check-provision-k8s-1.18

Just checking if nothing unexpected broke for other clusters.

**Comment by qinqon** [comment]
/hold cancel

job went well.

**Pull request merged**
