### PR TITLE
Update sonobuoy version to v0.56.9

### PR DESCRIPTION
**Pull request by oshoval**
Motivation: with this version we can upload the kubevirt conformance
artifact directory and have kubevirt k8s reporter results in case of a failure.

Depends on https://github.com/kubevirt/kubevirt/pull/8304
Once the above PR is merged, this PR must be merged (once there is a new nightly version)
because the changes are not backport compatible to older sonobuoy versions.

Beside that:
Fix typo on file name

### CODE REVIEW

**Comment by oshoval** [comment]
/test check-provision-k8s-1.24

WIP - just to see if it pass everything - Image based on https://github.com/kubevirt/kubevirt/pull/8304 (changes are needed because the default result dir is changed)

**Comment by oshoval** [comment]
/test check-provision-k8s-1.24

(it passed, did few changes so rechecking)

**Comment by oshoval** [comment]
/hold 

Depends on https://github.com/kubevirt/kubevirt/pull/8304
but once it is merged, this one must be merged as well

**Comment by oshoval** [comment]
/hold cancel

Will just keep as draft meanwhile

but reviews are welcome please

**Review by phoracek — APPROVED** [review]

**Comment by oshoval** [comment]
Updated all the other providers with the updated conformance.json

**Comment by oshoval** [comment]
Thanks

/hold because https://github.com/kubevirt/kubevirt/pull/8304
must be merged first

**Comment by oshoval** [comment]
Rebased and updated cluster-provision/k8s/1.24-psa/conformance.json

**Review by brianmcarey — COMMENTED** [review]
/lgtm

**Comment by oshoval** [comment]
https://github.com/kubevirt/kubevirt/pull/8304
is merged and there is new conformance
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirt-push-nightly-conformance/1578211134882713600

**Comment by oshoval** [comment]
/hold cancel

lets see the lanes are passing, they will gate the PR

**Pull request merged**
