### PR TITLE
Upgrade cri-o to version 1.25 for 1.25/6 providers

### PR DESCRIPTION
**Pull request by brianmcarey**
Signed-off-by: Brian Carey <bcarey@redhat.com>

### CODE REVIEW

**Review by jean-edouard — COMMENTED** [review]
It surprises me that https://cri-o.io/ still tells you to use the packages from the **retired** openSUSE Kubic project!
It looks like we are using a google mirror for it, which is probably a good idea since the official repository will probably disappear at some point.
I probably don't want to know why Centos (and other distros) don't just include cri-o in their base repos...
My only real concern here is, do we get 1.25.0 or 1.25.1 with this change? If it's 1.25.1 then I'll approve. Please confirm. Thank you!

**Comment by brianmcarey** [comment]
> It surprises me that https://cri-o.io/ still tells you to use the packages from the **retired** openSUSE Kubic project! It looks like we are using a google mirror for it, which is probably a good idea since the official repository will probably disappear at some point. I probably don't want to know why Centos (and other distros) don't just include cri-o in their base repos... My only real concern here is, do we get 1.25.0 or 1.25.1 with this change? If it's 1.25.1 then I'll approve. Please confirm. Thank you!

We mirror the latest stable release for `1.25` so yes I can confirm that this installs 1.25.1 - the job to mirror this actually pulls these from the kubic project and runs the following weekly  - https://github.com/kubevirt/project-infra/blob/11b6727636c83f9972090af3d28bdc6f7a9b725b/hack/mirror-crio.sh#L25

**Comment by brianmcarey** [comment]
/override check-up-kind-1.23-vgpu

Changes not related to vgpu lane.

**Review by dhiller — COMMENTED** [review]
/approve

**Review by dhiller — APPROVED** [review]

**Pull request merged**
