### PR TITLE
Add OKD provider 4.1.2

### PR DESCRIPTION
**Pull request by cynepco3hahue**
This provider includes custom libvirt image that makes possible to
test fencing flows without need for any W/A.

### CODE REVIEW

**Comment by cynepco3hahue** [comment]
@davidvossel Can you please review, it should fix all troubles with `SchedulingDisabled` for the master.

**Comment by cynepco3hahue** [comment]
hm looks like we lack nested virtualization support under some of hosts
```
INFO Creating infrastructure resources...
ERROR
ERROR Error: Error applying plan:
ERROR
ERROR 2 errors occurred:
ERROR * libvirt_domain.master: 1 error occurred:
ERROR * libvirt_domain.master: Error creating libvirt domain: virError(Code=1, Domain=10, Message='internal error: process exited while connecting to monitor: Could not access KVM kernel module: Permission denied
ERROR 2019-06-20T14:16:55.776486Z qemu-system-x86_64: failed to initialize KVM: Permission denied')
ERROR
ERROR
ERROR * module.bootstrap.libvirt_domain.bootstrap: 1 error occurred:
ERROR * libvirt_domain.bootstrap: Error creating libvirt domain: virError(Code=1, Domain=10, Message='internal error: qemu unexpectedly closed the monitor: Could not access KVM kernel module: Permission denied
ERROR 2019-06-20T14:16:56.358707Z qemu-system-x86_64: failed to initialize KVM: Permission denied')
ERROR
ERROR
ERROR
ERROR
ERROR
ERROR Terraform does not automatically rollback in the face of errors.
ERROR Instead, your Terraform state file has been partially updated with
ERROR any resources that successfully completed. Please address the error
ERROR above and apply again to incrementally change your infrastructure.
ERROR
ERROR
FATAL failed to fetch Cluster: failed to generate asset "Cluster": failed to create cluster: failed to apply using Terraform
failed to provision OKD cluster under the container okd-4.1.0-cluster
```

**Comment by cynepco3hahue** [comment]
hm nested virtualization enabled, so looks like it is kvm device permissions issue

**Comment by davidvossel** [comment]
i tested the provider out and it seemed to work well

**Comment by cynepco3hahue** [comment]
@davidvossel Can you please review again?

**Comment by davidvossel** [comment]
i was able to bring up the cluster, install kubevirt, and run a vmi successfully

**Pull request merged**
