### PR TITLE
dnsmasq: Mount /lib/modules to use ip6tables

### PR DESCRIPTION
**Pull request by qinqon**
After [1] ip6tables is used at dnsmasq.sh script this command
depends on a some kernel modules to be installed so
ip6tables try to load them but since the container has not
mounted the /lib/modules dir it cannot load them.

Signed-off-by: Quique Llorente <ellorent@redhat.com>

### CODE REVIEW

**Comment by maiqueb** [comment]
You're missing the link in the PR's description.

**Comment by oshoval** [comment]
Nice
but please consider it doesn't solve provision, the dnsmasq container there is triggered from bash script,
not the go cli, if i remember right.

**Review by oshoval — CHANGES_REQUESTED** [review]
Nice
but please consider it doesn't solve provision, the dnsmasq container there is triggered from bash script,
not the go cli, if i remember right.

**Comment by qinqon** [comment]
@oshoval right, let me add it to the `cli/cli`

**Comment by oshoval** [comment]
/lgtm
(just fill the [1] as Miguel said please)

**Review by oshoval — APPROVED** [review]

**Pull request merged**
