### PR TITLE
K8S 1.24 with PSA

### PR DESCRIPTION
**Pull request by xpivarc**
Create a new provider that enables [PSA](https://kubernetes.io/docs/concepts/security/pod-security-admission/) to be able to test Kubevirts integration. Setting policy enforcement on privileged means all components needs to integrate with PSA. Therefore this provider is only for development for now and hacks might be required in order to deploy other projects.

@dhiller @brianmcarey

### CODE REVIEW

**Comment by jean-edouard** [comment]
@xpivarc please add a PR description, explaining at least what PSA means, thanks!

**Comment by xpivarc** [comment]
/hold 
I need to test this locally but I have some connection issues.

**Comment by xpivarc** [comment]
/hold cancel
Works for me

**Comment by brianmcarey** [comment]
@xpivarc can you create a check-provision prow job for this provider so we can run the test against it here?

**Comment by xpivarc** [comment]
> @xpivarc can you create a check-provision prow job for this provider so we can run the test against it here?

Afaik it would run Kubevirt conformance tests and those will hardly pass unfortunatly. This is for developing and adopting our suite to be able to run with PSA enabled. Or do we run only Kubernetes conformance?

**Comment by brianmcarey** [comment]
> > @xpivarc can you create a check-provision prow job for this provider so we can run the test against it here?
> 
> Afaik it would run Kubevirt conformance tests and those will hardly pass unfortunatly. This is for developing and adopting our suite to be able to run with PSA enabled. Or do we run only Kubernetes conformance?

I think there is an environment variable we can set so it will skip the conformance tests for now: 
https://github.com/kubevirt/kubevirtci/blob/820bb50cab0d2ddee905d7024cd9beb905cbde97/cluster-provision/k8s/check-cluster-up.sh#L11

**Comment by xpivarc** [comment]
> > > @xpivarc can you create a check-provision prow job for this provider so we can run the test against it here?
> > 
> > 
> > Afaik it would run Kubevirt conformance tests and those will hardly pass unfortunatly. This is for developing and adopting our suite to be able to run with PSA enabled. Or do we run only Kubernetes conformance?
> 
> I think there is an environment variable we can set so it will skip the conformance tests for now:
> 
> https://github.com/kubevirt/kubevirtci/blob/820bb50cab0d2ddee905d7024cd9beb905cbde97/cluster-provision/k8s/check-cluster-up.sh#L11

Thanks! I will finish local testing and create the job.

**Comment by xpivarc** [comment]
/hold
On second look this seems to not work as expected.

**Review by brianmcarey — COMMENTED** [review]
/lgtm

**Review by brianmcarey — APPROVED** [review]
/approve 

This has to be merged to enable testing of PSA changes in kubevirt

**Pull request merged**
