### PR TITLE
Delete k8s-1.24-ipv6

### PR DESCRIPTION
**Pull request by oshoval**
In favor of k8s-1.25-ipv6

Signed-off-by: Or Shoval <oshoval@redhat.com>

### CODE REVIEW

**Comment by oshoval** [comment]
/cc @brianmcarey 

To take after we check it on kubevirt + merge https://github.com/kubevirt/project-infra/pull/2514

**Comment by oshoval** [comment]
/hold

depends on https://github.com/kubevirt/project-infra/pull/2514

**Comment by oshoval** [comment]
check-provision-k8s-1.24-ipv6 fails because the mentioned PR in the hold reason should be merged first

**Comment by oshoval** [comment]
Maybe there is check-provision-k8s-1.24-ipv6  because it was already on this PR before the project-infra was delete
lets override it please, or clone this PR and see that it doesn't appear indeed

amend after a while didn't help so far

**Comment by brianmcarey** [comment]
> Maybe there is check-provision-k8s-1.24-ipv6 because it was already on this PR before the project-infra was delete lets override it please, or clone this PR and see that it doesn't appear indeed
> 
> amend after a while didn't help so far

I don't see it in the list of jobs now

**Comment by oshoval** [comment]
> > Maybe there is check-provision-k8s-1.24-ipv6 because it was already on this PR before the project-infra was delete lets override it please, or clone this PR and see that it doesn't appear indeed
> > amend after a while didn't help so far
> 
> I don't see it in the list of jobs now

Right gone (it was when i wrote it)

**Review by brianmcarey — COMMENTED** [review]
/lgtm

**Review by brianmcarey — APPROVED** [review]
/approve

**Pull request merged**
