### PR TITLE
option added to set docker daemon proxy setting

### PR DESCRIPTION
**Pull request by kunalkushwaha**
--docker-proxy option added to gocli run command.
    This helps to set proxy setting for docker daemon
    without rebuilding of base VM image.
    
Fixes https://github.com/kubevirt/kubevirtci/issues/69 along with https://github.com/kubevirt/kubevirtci/pull/71

Signed-off-by: Kunal Kushwaha <kushwaha_kunal_v7@lab.ntt.co.jp>

### CODE REVIEW

**Comment by kunalkushwaha** [comment]
This PR enables to overwrite provision scripts while starting k8s cluster, which is helpful in settings like docker daemon proxy settings, downloading networking `[podnetwork].yaml` in `kubectl apply` command etc

```
$ ./cli run --mount-scripts /home/kunal/kubevirtci/k8s/scripts --nodes 1 --memory 5120M --cpu 5 --random-ports  --background --prefix k8s-1.10.11 --registry-volume
kubevirt_registry kubevirtci/k8s-1.10.11@sha256:b97e556795a56b9aa1763ddf3a49322b49f96877dccb7a164bbca779df078536 --ocp-port 8443
```

**Comment by rmohr** [comment]
> Avoids rebuilding of base VM image for every change in environment.

We deliberately want to rebuild the VM image. The trick is that all docker images are already cached and all rpms preinstalled. There seems to be only the issue that it fetches the flannel manifests from the internet again, that is why `kubectl apply` fails. 

I am not against the content of this PR, we can add it, but it is not a fix for #69. We should not fetch manifests from the internet again on `cluster-up`.

**Comment by kunalkushwaha** [comment]
Updated the PR for scope limited to docker daemon proxy settings as discussed in https://github.com/kubevirt/kubevirtci/issues/69#issuecomment-481569171

Along with #71 this will make cluster workable behind proxy. 

//cc @rmohr

**Comment by rmohr** [comment]
oh, we need gocli test runs ...

**Comment by rmohr** [comment]
@kunalkushwaha @slintes, sorry for the confusion, but the jobs were not actually active so far, I manually triggered them. Should work now. Let's see what the results say.

**Comment by rmohr** [comment]
@kunalkushwaha can you add the new gocli digest to the README.md? The digest from the job is `sha256:837ab7fff4e00d74ad9d6b8952c79dbf3df1db380da1fc13a87df34d70745003`. After that the PR can be merged.

**Comment by rmohr** [comment]
/hold

digest needs to be updated.

**Comment by kunalkushwaha** [comment]
> The digest from the job is sha256:837ab7fff4e00d74ad9d6b8952c79dbf3df1db380da1fc13a87df34d70745003. After that the PR can be merged.

@rmohr thanks. I have updated README.md  with suggested digest.

**Pull request merged**
