### PR TITLE
update CNAO to 0.20.0

### PR DESCRIPTION
**Pull request by phoracek**
The current manifests referenced ancient version 0.8.0.

Signed-off-by: Petr Horacek <phoracek@redhat.com>

### CODE REVIEW

**Comment by cynepco3hahue** [comment]
@phoracek You will need to provision all providers that install network addons.

**Comment by phoracek** [comment]
@cynepco3hahue that means calling some CI commands (help me here please) and ...?

**Comment by cynepco3hahue** [comment]
it should be `/test push-<provider_name>` after from the job log you can get new image hash and update the README and all relevant places with new hash

**Comment by SchSeba** [comment]
@phoracek there is also this PR https://github.com/kubevirt/kubevirtci/pull/147 that you can use

**Comment by phoracek** [comment]
@SchSeba right, I think we should finish that one. Thanks for sharing!

**Pull request closed without merging**
