### PR TITLE
Remove cluster-provision/manifests

### PR DESCRIPTION
**Pull request by qinqon**
They are no longer used.

Signed-off-by: Quique Llorente <ellorent@redhat.com>

### CODE REVIEW

**Comment by enp0s3** [comment]
@qinqon Hi. Can you please elaborate on why aren't they used anymore? thanks

**Comment by qinqon** [comment]
> @qinqon Hi. Can you please elaborate on why aren't they used anymore? thanks

Those manifests were moved to cluster-provisiong/k8s-1.yz/manifests to encapsulate them per kubernetes version and be able to do small tunning.

**Review by enp0s3 — APPROVED** [review]
Thank you!
/approve

**Pull request merged**
