### PR TITLE
Pin okd-4.3 to the used release image

### PR DESCRIPTION
**Pull request by qinqon**
Signed-off-by: Quique Llorente <ellorent@redhat.com>

### CODE REVIEW

**Comment by rmohr** [comment]
/approve
/hold

I guess this is mostly important for future rebuilds, and the rebuilds are passing. Can we merge it?

**Comment by cynepco3hahue** [comment]
@rmohr The question, how long this release will exist :worried:

**Comment by qinqon** [comment]
well, it's already gone :-(

**Comment by rmohr** [comment]
lol

/close

**Pull request closed without merging**
