### PR TITLE
enable audit logs for os-3.11.0-multus

### PR DESCRIPTION
**Pull request by mfranczy**
- enable audit log for multus
- os-3.11.0 provisioner refactoring

### CODE REVIEW

**Comment by mfranczy** [comment]
@cynepco3hahue I forgot to add audit logs for multus, so this PR should fix it.

**Comment by cynepco3hahue** [comment]
@mfranczy Can you delete the debug commit, I think the problem solved by @rmohr under https://github.com/kubevirt/project-infra/pull/119

**Comment by mfranczy** [comment]
@cynepco3hahue done

**Comment by cynepco3hahue** [comment]
@mfranczy Can you update hash if multus image under all relevant places?

**Comment by mfranczy** [comment]
@cynepco3hahue done

**Comment by mfranczy** [comment]
ah wait, not everywhere yet

**Comment by mfranczy** [comment]
now all relevant places are up to date.

**Pull request merged**
