### PR TITLE
Remove not supported kind 1.19

### PR DESCRIPTION
**Pull request by xpivarc**
Active supported versions are 1.21,1.22,1.23.

Signed-off-by: L. Pivarc <lpivarc@redhat.com>

### CODE REVIEW

**Comment by ormergi** [comment]
We can also remove https://github.com/kubevirt/kubevirtci/blob/main/cluster-up/cluster/kind/podpreset.sh
is was necessary for kind 1.19 and below setups.

**Comment by enp0s3** [comment]
> We can also remove https://github.com/kubevirt/kubevirtci/blob/main/cluster-up/cluster/kind/podpreset.sh is was necessary for kind 1.19 and below setups.

@xpivarc WDYT?

**Comment by dhiller** [comment]
/approve

Sane thing to do, as we don't even run a check-up for 1.19 any more.

/hold

Waiting for kind changes to land in kubevirt/kubevirt, after which we can remove the hold.

**Comment by EdDev** [comment]
> > We can also remove https://github.com/kubevirt/kubevirtci/blob/main/cluster-up/cluster/kind/podpreset.sh is was necessary for kind 1.19 and below setups.
> 
> @xpivarc WDYT?

I agree, this is relevant only to 1.19 and below and should be removed as part of this PR.
Except that, it is great to see things removed.

Placing a hold so it will not be missed.
/hold

**Comment by xpivarc** [comment]
> > > We can also remove https://github.com/kubevirt/kubevirtci/blob/main/cluster-up/cluster/kind/podpreset.sh is was necessary for kind 1.19 and below setups.
> > 
> > 
> > @xpivarc WDYT?
> 
> I agree, this is relevant only to 1.19 and below and should be removed as part of this PR. Except that, it is great to see things removed.
> 
> Placing a hold so it will not be missed. /hold

@EdDev @ormergi 
I agree. I would appreciate it if you point me to why we can do this onwards so I can provide a nice commit message.

**Comment by EdDev** [comment]
> I agree. I would appreciate it if you point me to why we can do this onwards so I can provide a nice commit message.

The PodPresets feature has been removed in Kubernetes 1.20.

> The v1alpha1 PodPreset API and admission plugin has been removed with no built-in replacement. Admission webhooks can be used to modify pods on creation. (https://github.com/kubernetes/kubernetes/pull/94090, [@deads2k](https://github.com/deads2k)) [SIG API Machinery, Apps, CLI, Cloud Provider, Scalability and Testing]

Ref: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.20.md#deprecation
(last bullet)

**Comment by xpivarc** [comment]
> https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.20.md#deprecation

Thank you!

**Review by EdDev — APPROVED** [review]

**Pull request merged**
