### PR TITLE
Nominate brianmcarey to be approver

### PR DESCRIPTION
**Pull request by xpivarc**
I believe Brian is an active maintainer in our CI and should have the right to accept PRs in this repository.

### CODE REVIEW

**Comment by xpivarc** [comment]
/hold
/cc @rmohr @davidvossel @vladikr @qinqon @enp0s3 @jean-edouard @phoracek @dhiller @awels 

Please leave your objections or approve.

**Comment by rmohr** [comment]
> I believe Brian is an active maintainer in our CI and should have the right to accept PRs in this repository.

Absolutely! :tada: 

/lgtm

**Review by phoracek — APPROVED** [review]

**Review by jean-edouard — APPROVED** [review]

**Review by dhiller — APPROVED** [review]
Totally! Long time overdue!

/approve

**Comment by xpivarc** [comment]
/unhold
I think we have a majority here. Thank you all and @brianmcarey !

**Pull request merged**
