### PR TITLE
psa: Fix bash error

### PR DESCRIPTION
**Pull request by oshoval**
In case `KUBEVIRT_PSA` is not defined,
bash has an error `unary operator expected`,
because "==" is a binary operator.
Fix it by setting its default value to false.

Signed-off-by: Or Shoval <oshoval@redhat.com>

### CODE REVIEW

**Comment by oshoval** [comment]
```

time="2022-12-18T10:13:14Z" level=info msg="removing the ssh.sh script"
time="2022-12-18T10:13:14Z" level=info msg="removing the ssh_ready mark"
Error: crun: the container `a57c39feac20f2d3b9e8ed1ae1fe274730aa901cc2802c723dc84252de0a55ba` is not running: OCI runtime error
```

Not related 
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirtci/935/check-provision-k8s-1.24/1604415794333093888

**Review by maiqueb — APPROVED** [review]
tks.

**Review by enp0s3 — COMMENTED** [review]
/approve

**Comment by oshoval** [comment]
Thanks

/retest

**Review by xpivarc — APPROVED** [review]

**Pull request merged**
