### PR TITLE
add CPUNodeDiscovery and HypervStrictCheck as default featureGates

### PR DESCRIPTION
**Pull request by kwiesmueller**
Default CPUNodeDiscovery and HypervStrictCheck to enabled as node-labeler is now a part of kubevirt.
/cc @jean-edouard @omeryahud @stu-gott

### CODE REVIEW

**Comment by kwiesmueller** [comment]
This is enabled by https://github.com/kubevirt/kubevirt/pull/5324

**Review by stu-gott — COMMENTED** [review]
/approve

**Comment by xpivarc** [comment]
/hold

I believe this is not the way to go.
These feature gates would be overridden [here](https://github.com/kubevirt/kubevirt/blob/master/tests/utils.go#L765) if the flag is not provided. Maybe we should add them there.

**Comment by kwiesmueller** [comment]
Closing this as the HCO case is handled now and I'm working on a better featureGate API design.

**Comment by stu-gott** [comment]
@kwiesmueller for future reference on this PR, do you have a link to the HCO PR?

**Comment by kwiesmueller** [comment]
Sure: https://github.com/kubevirt/hyperconverged-cluster-operator/pull/1281

**Pull request closed without merging**
