### PR TITLE
Add multinic to okd4 provider

### PR DESCRIPTION
**Pull request by qinqon**
Signed-off-by: Quique Llorente <ellorent@redhat.com>

### CODE REVIEW

**Comment by qinqon** [comment]
Manually testing this we have the following interfaces

```bash
root@a9f379afaed9 /]# virsh domiflist test-1-sfgtk-master-0
Interface  Type       Source     Model       MAC
-------------------------------------------------------
vnet0      network    test-1-sfgtk virtio      66:4f:16:3f:5f:0f
vnet1      network    test-1-sfgtk virtio      52:54:00:4b:01:01
vnet2      network    test-1-sfgtk virtio      52:54:00:4b:01:02
vnet3      network    test-1-sfgtk virtio      52:54:00:4b:01:03
vnet4      network    test-1-sfgtk virtio      52:54:00:4b:01:04

[root@a9f379afaed9 /]# virsh domiflist test-1-sfgtk-worker-0-7l58x
Interface  Type       Source     Model       MAC
-------------------------------------------------------
vnet5      network    test-1-sfgtk virtio      aa:5f:d0:99:c7:94
vnet6      network    test-1-sfgtk virtio      52:54:00:4b:02:01
vnet7      network    test-1-sfgtk virtio      52:54:00:4b:02:02
vnet8      network    test-1-sfgtk virtio      52:54:00:4b:02:03
vnet9      network    test-1-sfgtk virtio      52:54:00:4b:02:04

[root@a9f379afaed9 /]# 
```

**Comment by cynepco3hahue** [comment]
@qinqon We should first merge project-infra PR

**Comment by qinqon** [comment]
/hold there is something not right at gocli

```
Run the cluster
+ NUM_SECONDARY_NICS='%!s(uint=4)'
+ chown root:kvm /dev/kvm

```

**Comment by phoracek** [comment]
> there is something not right at gocli
Told you @cynepco3hahue, I'm Mr. Goldfish.

**Pull request merged**
