### PR TITLE
Fix gocli image publication

### PR DESCRIPTION
**Pull request by fgimenez**
Signed-off-by: Federico Gimenez <fgimenez@redhat.com>

### CODE REVIEW

**Comment by dhiller** [comment]
check-provision 1.20 looks suspicious:
```
+ ./sonobuoy run --wait --config /home/prow/go/src/github.com/kubevirt/kubevirtci/cluster-provision/k8s/1.20/conformance.json
time="2021-01-15T12:30:58Z" level=warning msg="The maximum supported Kubernetes version is 1.19.99, but the server version is v1.20.1. Sonobuoy will continue but unexpected results may occur."
```

https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirtci/525/check-provision-k8s-1.20/1350054117011099648#1:build-log.txt%3A3961

**Comment by rmohr** [comment]
@dhiller good observation. We have to bump sonobuoy then.

**Comment by fgimenez** [comment]
It finally failed https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirtci/525/check-provision-k8s-1.20/1350054117011099648#1:build-log.txt%3A3973 @dhiller can this be related to the warning you mentioned?

**Pull request merged**
