### PR TITLE
Use cluster container images from quay.io by default

### PR DESCRIPTION
**Pull request by fgimenez**
Requires https://github.com/kubevirt/project-infra/pull/789

cc/ @rmohr 

Signed-off-by: Federico Gimenez <fgimenez@redhat.com>

### CODE REVIEW

**Review by rmohr — CHANGES_REQUESTED** [review]
I think that we also need to adjust the publish.sh script in the root folder to push to `quay.io/kubevirtci` instead of `kubevirtci`.

**Comment by rmohr** [comment]
/lgtm
/approve
/hold

Let's merge this in a coordinated fashion. Once all lanes are green, we should first merge the new job definitions. Then this one, so that the postsubmit can succeed.

**Review by rmohr — APPROVED** [review]

**Comment by fgimenez** [comment]
> Let's merge this in a coordinated fashion. Once all lanes are green, we should first merge the new job definitions. Then this one, so that the postsubmit can succeed.

@rmohr ok lanes are green but they required a few more changes, PTAL. Ready to go ahead with https://github.com/kubevirt/project-infra/pull/789

**Comment by rmohr** [comment]
/lgtm
/hold

Once the other PR is merged we should give it a few minutes since the jobs are not immediately updated in the running components.

**Pull request merged**
