### PR TITLE
Don't run etcd on memory by default

### PR DESCRIPTION
**Pull request by rmohr**
When reviewing #499 I missed that it would run etcd by default in memory. Switching the default to false.

### CODE REVIEW

**Review by fgimenez — APPROVED** [review]
/lgtm
/approve
/hold

Feel free to unhold when ready. not sure if my approve and hold commands are taken into account here, just in case :)

**Review by ormergi — APPROVED** [review]

**Comment by ormergi** [comment]
Are we going to enable it at the provider level?

**Comment by rmohr** [comment]
> Are we going to enable it at the provider level?
> If so which provider and when? :)

We can experiment with it on a PR in kubevirt/kubevirt. My first experiment with unconditionally enabling it did not go so well. With your PR we can now directly experiment in kubevirt/kubevirt and decide then if we enable it.

**Comment by oshoval** [comment]
https://github.com/kubevirt/kubevirtci/pull/513 is a fix for
the failing https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirtci/517/check-up-kind-1.17-sriov/1347105297558147072

**Comment by rmohr** [comment]
@oshoval overriding then. Thanks.

/hold cancel
/override check-up-kind-1.17-sriov

**Pull request merged**
