### PR TITLE
bump-cdi script: Update script to include also k8s-1.22-ipv6

### PR DESCRIPTION
**Pull request by oshoval**
Update the regex in order to include also k8s-1.22-ipv6

Signed-off-by: Or Shoval <oshoval@redhat.com>

### CODE REVIEW

**Comment by oshoval** [comment]
/cc @dhiller 

can you please take a look ?

**Comment by oshoval** [comment]
/cc @qinqon
can you please take a look ?

**Review by dhiller — COMMENTED** [review]
/approve

**Comment by oshoval** [comment]
Thanks

/retest

**Pull request merged**
