### PR TITLE
Add force flag, auto detect latest provision dir if not given

### PR DESCRIPTION
**Pull request by dhiller**
This is a preparation to use the script to update CDI whenever a new provider is created via the job.

It does two things:
 - adds force flag `-f` to be able to replace cdi manifests with newer version
 - auto detects the latest provider directory in case no argument is given

This way we can call the script after a new provider is created to update the CDI manifest to the latest version.

Signed-off-by: Daniel Hiller <dhiller@redhat.com>

/cc @oshoval @enp0s3

### CODE REVIEW

**Review by oshoval — COMMENTED** [review]
can you add please a flag that force specific version as well (line 44) ?
this way we can force update the the same version that kubevirt uses
kubevirt doesn't use latest always, for example now it uses 1.36.0 
and the latest is 37+

once we have this, we can add code in the provision that will check what kubevirt uses and fetch that version,
kubevirtci uses the CDI yaml only for prefetching the images, so it will make kubevirtci always aligned to the actual kubevirt it uses

**Comment by dhiller** [comment]
> can you add please a flag that force specific version as well (line 44) ?
> this way we can force update the the same version that kubevirt uses
> kubevirt doesn't use latest always, for example now it uses 1.36.0
> and the latest is 37+
> 
> once we have this, we can add code in the provision that will check what kubevirt uses and verify that version is used using the script (else fail if there is a diff), and use the same method in order to actual bump when needed,
> kubevirtci uses the CDI yaml only for prefetching the images, so it will make kubevirtci always aligned to the actual kubevirt it uses
> 
> Its not mandatory, as we can achieve this purpose also without the script, it will just improve the script i think.

IMHO the long term goal should be that we add the CDI spinup here as we do with most of the other features (CNAO, Prometheus, etc) and kubevirt just consumes what is baked in here, as it does with the other things. In other words, I'd rather remove all the CDI spinup from KubeVirt and add a flag, like KUBEVIRT_DEPLOY_CDI or the like here: https://github.com/kubevirt/kubevirtci/blob/1ad0cbd6f8621e0d8583c921581960a46155098b/cluster-up/cluster/ephemeral-provider-common.sh#L93

What do others think?

/cc @rmohr @aglitke @awels

**Comment by dhiller** [comment]
/close

Will create another one where I'll incorporate this change to update cdi manifest while also adding an install for cdi

**Comment by oshoval** [comment]
> > can you add please a flag that force specific version as well (line 44) ?
> > this way we can force update the the same version that kubevirt uses
> > kubevirt doesn't use latest always, for example now it uses 1.36.0
> > and the latest is 37+
> > once we have this, we can add code in the provision that will check what kubevirt uses and verify that version is used using the script (else fail if there is a diff), and use the same method in order to actual bump when needed,
> > kubevirtci uses the CDI yaml only for prefetching the images, so it will make kubevirtci always aligned to the actual kubevirt it uses
> > Its not mandatory, as we can achieve this purpose also without the script, it will just improve the script i think.
> 
> IMHO the long term goal should be that we add the CDI spinup here as we do with most of the other features (CNAO, Prometheus, etc) and kubevirt just consumes what is baked in here, as it does with the other things. In other words, I'd rather remove all the CDI spinup from KubeVirt and add a flag, like KUBEVIRT_DEPLOY_CDI or the like here:
> 
> https://github.com/kubevirt/kubevirtci/blob/1ad0cbd6f8621e0d8583c921581960a46155098b/cluster-up/cluster/ephemeral-provider-common.sh#L93

https://github.com/kubevirt/kubevirt/pull/6339
I am already working on it

Note that i think we still need to align CDI images between kubevirt and kubevirtci, but it can be done on other PR

> 
> What do others think?
> 
> /cc @rmohr @aglitke @awels

**Pull request closed without merging**
