### PR TITLE
cluster-provision, Prefetch cdi images

### PR DESCRIPTION
**Pull request by oshoval**
Prefetch CDI images for k8s-1.19, k8s-1.20

Signed-off-by: Or Shoval <oshoval@redhat.com>

### CODE REVIEW

**Comment by oshoval** [comment]
Failures here are not due to the PR, it happens on other PRs as well

**Comment by enp0s3** [comment]
@oshoval Hi. Thank you for the PR! a general question - why didn't you do the prefetch for 1.21 as well?

**Comment by oshoval** [comment]
> @oshoval Hi. Thank you for the PR! a general question - why didn't you do the prefetch for 1.21 as well?

I did here
https://github.com/kubevirt/kubevirtci/pull/659
it has other mechanism so splitted

**Pull request merged**
