### PR TITLE
Turn on debug logs for kind delete

### PR DESCRIPTION
**Pull request by xpivarc**
This could help debugging failing delete operation

Signed-off-by: L. Pivarc <lpivarc@redhat.com>

### CODE REVIEW

**Review by ormergi — APPROVED** [review]
Did you find something interesting with the new logs?

**Comment by xpivarc** [comment]
> Did you find something interesting with the new logs?

I think we need to merge this and see if it gives us something on failure.

**Comment by dhiller** [comment]
/approve

/hold

holding for kind changes to land in kubevirt/kubevirt

**Comment by ormergi** [comment]
> I think we need to merge this and see if it gives us something on failure.
> 
> Unfortunately, I don't have hw available.

@xpivarc there is no need to merge it just to verfiy it works :slightly_smiling_face:
Please test it first by creating a draft at kubevirt/kubevirt with this PR changes, for example:
https://github.com/kubevirt/kubevirt/pull/7524

**Comment by dhiller** [comment]
> > I think we need to merge this and see if it gives us something on failure.
> > Unfortunately, I don't have hw available.
> 
> @xpivarc there is no need to merge it just to verfiy it works slightly_smiling_face Please test it first by creating a draft at kubevirt/kubevirt with this PR changes, for example: [kubevirt/kubevirt#7524](https://github.com/kubevirt/kubevirt/pull/7524)

Good point, let's wait for a test whether this works on kubevirt/kubevirt

/hold

**Comment by xpivarc** [comment]
> 

Thanks, in progress https://github.com/kubevirt/kubevirt/pull/7527

**Pull request closed without merging**
