### PR TITLE
Bump k8s providers

### PR DESCRIPTION
**Pull request by fgimenez**
Bumping provider versions to pick this fix https://github.com/kubernetes/kubernetes/pull/102576 that has been already backported and published. It is expected to stabilize the storage lanes, some of the failing builds are showing the same error in the logs as the issue fixed by that patch, for instance https://storage.googleapis.com/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-1.19-sig-storage/1421536336380170240/artifacts/k8s-reporter/nodes/1_journal_kubelet_node02.log

/cc @maya-r @brybacki 

Signed-off-by: Federico Gimenez <fgimenez@redhat.com>

### CODE REVIEW

**Comment by dhiller** [comment]
1.19 job failure was likely caused by an error that was ignored during install of k8s tools: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirtci/661/check-provision-k8s-1.19/1425808634591318016#1:build-log.txt%3A2159

**Review by dhiller — APPROVED** [review]
/approve

Looks good to me, as far as I can see the kubevirtci conformance tests all ran into a timeout. Retest triggerd, let's see how that goes

**Comment by phoracek** [comment]
Tests on 1.20 and 1.21 seem to fail on IPv6. Let's see if it consistently fails.

**Comment by dominikholler** [comment]
Previous tests runs failed on

[sig-apps] StatefulSet [k8s.io] Basic StatefulSet functionality [StatefulSetBasic] should perform rolling updates and roll backs of template modifications [Conformance] expand_more
[sig-apps] StatefulSet [k8s.io] Basic StatefulSet functionality [StatefulSetBasic] should perform canary updates and phased rolling updates of template modifications [Conformance] expand_more

**Pull request merged**
