### PR TITLE
bump kind script: Fix script and generalize it

### PR DESCRIPTION
**Pull request by oshoval**
**What this PR does / why we need it**:
Sometimes the version appears after
"1.29.x:", so support this case as well.

Allow using the script for any kind provider we have.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Checklist**

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

**Release note**:

```release-note
None
```

### CODE REVIEW

**Comment by zhlhahaha** [comment]
> @vladikr FYI please You might want to consider changing the kind-1.27-vpgu to kind-vgpu so once it is bumped, no need to update the CI jobs
> 
> @zhlhahaha FYI please

Hi @oshoval , good to see the [sriov](https://github.com/kubevirt/kubevirtci/commit/8537a6725d07b1f9e220097c5e01a126cf98d3f3) patch has merged. I am busy this week, and I will follow up in the next week to make the kind-1.28 sync with sriov.

**Comment by oshoval** [comment]
> > @vladikr FYI please You might want to consider changing the kind-1.27-vpgu to kind-vgpu so once it is bumped, no need to update the CI jobs
> > @zhlhahaha FYI please
> 
> Hi @oshoval , good to see the [sriov](https://github.com/kubevirt/kubevirtci/commit/8537a6725d07b1f9e220097c5e01a126cf98d3f3) patch has merged. I am busy this week, and I will follow up in the next week to make the kind-1.28 sync with sriov.

Hi run rush, thanks

**Comment by oshoval** [comment]
/cc @EdDev 
can you take a look please?

**Comment by oshoval** [comment]
vgpu is flaky not due to this PR

**Review by EdDev — APPROVED** [review]
Nice, thanks.

**Comment by zhlhahaha** [comment]
> Note that on our CI 0.20 doesnt work out of the box

Hi, @oshoval Would you mind to give more information on this? I am not quite sure what it means.

**Comment by oshoval** [comment]
> > Note that on our CI 0.20 doesnt work out of the box
> 
> Hi, @oshoval Would you mind to give more information on this? I am not quite sure what it means.

Hi sure
when i tried to bump kind-sriov to use kind version v0.20.0, with either k8s 1.28 / 1.29 image
it didnt even manage to create the cluster on CI (locally it did work)
it failed when tried to join nodes, i didnt investigate deeper, and for now just bumped to v0.19.0 / k8s-1.28

**Comment by zhlhahaha** [comment]
> Hi sure when i tried to bump kind-sriov to use kind version v0.20.0, with either k8s 1.28 / 1.29 image it didnt even manage to create the cluster on CI (locally it did work) it failed when tried to join nodes (nodes >=2), i didnt investigate deeper, and for now just bumped to v0.19.0 / k8s-1.28 maybe we just need to bump the bootstrap-legacy image (legacy because we still use docker on CI)

Interesting, I saw kind v0.21.0 released 3 days ago, have you tried it?

**Comment by oshoval** [comment]
> > Hi sure when i tried to bump kind-sriov to use kind version v0.20.0, with either k8s 1.28 / 1.29 image it didnt even manage to create the cluster on CI (locally it did work) it failed when tried to join nodes (nodes >=2), i didnt investigate deeper, and for now just bumped to v0.19.0 / k8s-1.28 maybe we just need to bump the bootstrap-legacy image (legacy because we still use docker on CI)
> 
> Interesting, I saw kind v0.21.0 released 3 days ago, have you tried it?

not yet

**Pull request merged**
