### PR TITLE
Disable endpointslices

### PR DESCRIPTION
**Pull request by qinqon**
Disable endpointslices it's activated by default at k8s-1.19
    
At k8s-1.17 endpointslices was introduced with as an opt-in but at k8s-1.19
is opt-out with a feture gate a kube-proxy, what we observe at kubevirt is that
virt-operator is re-create services very fast so the endpointslices does not get
re-created by the k8s controller, it's possible to reproduces this with at simple
http pod server and service.
    
k8s issue: https://github.com/kubernetes/kubernetes/issues/94720

### CODE REVIEW

**Comment by qinqon** [comment]
Looks like endpointslices may have some raices and that affects at kubevirt https://github.com/kubernetes/kubernetes/issues/94720

**Comment by qinqon** [comment]
/cc @dhiller 
This could be it.

**Review by dhiller — COMMENTED** [review]
/lgtm
/approve
/hold let's wait what the job is saying

**Review by dhiller — APPROVED** [review]

**Pull request merged**
