### PR TITLE
Don't wait for ceph toolbox to be deployed: we no longer deploy it

### PR DESCRIPTION
**Pull request by maya-r**
[We are failing to cluster-up now.](https://github.com/kubevirt/kubevirt/pull/8292#issuecomment-1219208441)

### CODE REVIEW

**Review by oshoval — APPROVED** [review]
Thanks
Can you please update the PR desc with the info inline ?

**Comment by maya-r** [comment]
cc @brianmcarey

**Review by brianmcarey — APPROVED** [review]
/approve

**Comment by oshoval** [comment]
I think we need to allow parallel runs of check-provision-k8s-1.2x ?
else when there are few kubevirtci PRs, it pending long time

**Pull request merged**
