### PR TITLE
Fix K8s 1.17, 1.18 provisioning

### PR DESCRIPTION
**Pull request by oshoval**
Update k8s 1.17/8 install to overcome conflict errors
    
Due to a bug in k8s there is a conflict issue
during provisioning.
    
https://github.com/kubernetes/kubernetes/issues/92463

Fixes: #394

### CODE REVIEW

**Comment by oshoval** [comment]
check-provision-k8s-fedora-1.17.0 
fails on something not related to this PR
should we maintain this lane ?

**Comment by rmohr** [comment]
> check-provision-k8s-fedora-1.17.0
> fails on something not related to this PR
> should we maintain this lane ?

@fedepaol is it still used somewhere?

**Comment by rmohr** [comment]
/lgtm

Let's wait for sonobuoy to confirm that the clusters are solid.

**Comment by oshoval** [comment]
/hold, 
will reprovision hashes once you say it good, thanks

**Comment by oshoval** [comment]
/hold
will reprovision hashes once you say it good, thanks

**Comment by rmohr** [comment]
The two clusters look good. Not sure if the fedora cluster is used. You could check kubevirt/project-infra  if some tests are run against it on prow.

**Comment by oshoval** [comment]
> The two clusters look good. Not sure if the fedora cluster is used. You could check kubevirt/project-infra if some tests are run against it on prow.

Just kubevirtci itself use it.
https://github.com/kubevirt/project-infra/blob/master/github/ci/prow/files/jobs/kubevirt/kubevirtci/kubevirtci-presubmits.yaml

**Comment by oshoval** [comment]
/hold cancel
updated hashes with fresh provisioned images.

**Pull request merged**
