### PR TITLE
cluster-up: bump multus

### PR DESCRIPTION
**Pull request by ormergi**
Bump Multus CNI to version v4.0.2 [[1]](https://github.com/k8snetworkplumbingwg/multus-cni/pkgs/container/multus-cni/96204454?tag=v4.0.2) [[2]](https://github.com/k8snetworkplumbingwg/multus-cni/releases/tag/v4.0.2) on providers:
- k8s-1.27
- k8s-1.28
- k8s-1.29 
- kind-1.27-sriov

Notes:
- Multus operate in thin plugin mode as before.
- Dropped Kustomize usage for Multus manifest in favor of modified manifest as in other providers.
  For this specific use case, using Kustomize doesn't worth the overhead.

[1] https://github.com/k8snetworkplumbingwg/multus-cni/pkgs/container/multus-cni/96204454?tag=v4.0.2
[2] https://github.com/k8snetworkplumbingwg/multus-cni/releases/tag/v4.0.2

### CODE REVIEW

**Comment by ormergi** [comment]
check-provision-k8s-1.29 job failed due to timeout as it took more then 3 hours
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirtci/1118/check-provision-k8s-1.29/1747224991079862272 

Looking into the job history, usually it takes around 2:30 hours
https://prow.ci.kubevirt.io/job-history/gs/kubevirt-prow/pr-logs/directory/check-provision-k8s-1.29

**Comment by oshoval** [comment]
```
Complete!
+ rm -f /etc/sysconfig/network-scripts/ifcfg-eth0
+ nmcli connection add con-name eth0 ifname eth0 type ethernet
Connection 'eth0' (d2adf2b5-f837-4fd4-8345-bce88c8d41e7) successfully added.
+ rm -f /etc/machine-id
+ touch /etc/machine-id
time="2024-01-16T12:05:01Z" level=info msg="shutting down the node"
time="2024-01-16T12:05:03Z" level=info msg="removing the ssh.sh script"
time="2024-01-16T12:05:04Z" level=info msg="removing the ssh_ready mark"
time="2024-01-16T12:05:05Z" level=info msg="waiting for the node to stop"
```

this is a bug that happens every now and then and hangs the process
just retest imo

**Comment by ormergi** [comment]
Thanks, retesting
/test check-provision-k8s-1.29

**Comment by EdDev** [comment]
> * Multus operate in thin plugin mode as before.

I think this is not the default in v4.
We should use the default one.

**Comment by ormergi** [comment]
> I think this is not the default in v4. We should use the default one.

The manifest was taken from Multus repo and modified to Kubervirt needs, its the manifest for Multus on thin mode:
https://github.com/k8snetworkplumbingwg/multus-cni/blob/v4.0.2/docs/quickstart.md#installation
https://github.com/k8snetworkplumbingwg/multus-cni/blob/v4.0.2/deployments/multus-daemonset.yml

Note that there is another manifest for thick mode.

**Comment by EdDev** [comment]
> > I think this is not the default in v4. We should use the default one.
> 
> The manifest was taken from Multus repo and modified to Kubervirt needs, its the manifest for Multus on thin mode: https://github.com/k8snetworkplumbingwg/multus-cni/blob/v4.0.2/docs/quickstart.md#installation https://github.com/k8snetworkplumbingwg/multus-cni/blob/v4.0.2/deployments/multus-daemonset.yml
> 
> Note that there is another manifest for thick mode.

I think v4 is suppose to be deployed by default using the thick mode.
I do not think we need to keep the thin mode around anymore, we should be as close as possible to what users will deploy by default.

**Comment by ormergi** [comment]
> I think v4 is suppose to be deployed by default using the thick mode. I do not think we need to keep the thin mode around anymore, we should be as close as possible to what users will deploy by default.

We do that with CNAO, it deploys the same version but with thick mode.
Eventually we need both setups to test in-place and migration base hotplug, right?

**Comment by EdDev** [comment]
> > I think v4 is suppose to be deployed by default using the thick mode. I do not think we need to keep the thin mode around anymore, we should be as close as possible to what users will deploy by default.
> 
> We do that with CNAO, it deploys the same version but with thick mode. Eventually we need both setups to test in-place and migration base hotplug, right?

Yes. And we can deploy the same with CNAO on these lanes as well.
The only difference is that additional dynamic network component that we deploy on some of the setups.

**Comment by ormergi** [comment]
Closing this PR for now, we decided to have CNAO deploy Multus in both migration-based and in-place hotplug NICs tests and deploy the dynamic-network-controller conditionally (so it will be deployed at in-place hotplug NICs periodic lane only).

/close

**Comment by ormergi** [comment]
Superseded by #1125

**Pull request closed without merging**
