### PR TITLE
Add Fedora 40 containerdisk

### PR DESCRIPTION
**Pull request by acardace**
The new image provides an updated kernel which is needed for memory hotplug testing as virtio-mem requires the guest kernel to be 5.16+ at least.

**What this PR does / why we need it**:
Add Fedora 40 to help with memory hotplug testing.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Checklist**

This checklist is not enforcing, but it's a reminder of items that could be relevant to every PR.
Approvers are expected to review this list.

- [ ] Design: A [design document](https://github.com/kubevirt/community/tree/main/design-proposals) was considered and is present (link) or not required
- [ ] PR: The PR description is expressive enough and will help future contributors
- [ ] Code: [Write code that humans can understand](https://en.wikiquote.org/wiki/Martin_Fowler#code-for-humans) and [Keep it simple](https://en.wikipedia.org/wiki/KISS_principle)
- [ ] Refactor: You have [left the code cleaner than you found it (Boy Scout Rule)](https://learning.oreilly.com/library/view/97-things-every/9780596809515/ch08.html)
- [ ] Upgrade: Impact of this change on upgrade flows was considered and addressed if required
- [ ] Testing: New code requires [new unit tests](https://github.com/kubevirt/kubevirt/blob/main/docs/reviewer-guide.md#when-is-a-pr-good-enough). New features and bug fixes require at least on e2e test
- [ ] Documentation: A [user-guide update](https://github.com/kubevirt/user-guide/) was considered and is present (link) or not required. You want a user-guide update if it's a user facing feature / API change.
- [ ] Community: Announcement to [kubevirt-dev](https://groups.google.com/g/kubevirt-dev/) was considered

**Release note**:

```release-note
Bump fedora-with-test-tooling image to Fedora 40
```

### CODE REVIEW

**Comment by brianmcarey** [comment]
It would be worth building a image and creating a test PR against kubevirt as this will likely break a number of network tests which I hit issues with previously trying to update this image to f39. 
https://github.com/kubevirt/kubevirt/pull/11419 

i can try and get an image built for you.

**Comment by brianmcarey** [comment]
Running tests here - https://github.com/kubevirt/kubevirt/pull/12105

**Comment by acardace** [comment]
@brianmcarey thank you!

**Review by ormergi — COMMENTED** [review]
Hi Antonio, thanks for the PR

Can we update the image we using in kubevirt test to fedora 40 instead of introducing another fedora image?
https://github.com/kubevirt/kubevirtci/blob/main/cluster-provision/images/vm-image-builder/fedora-with-test-tooling/os-variant

**Pull request closed without merging**
