### PR TITLE
k8s providers: Delete k8s-1.21

### PR DESCRIPTION
**Pull request by oshoval**
We are using now 1.22-1.24

Delete old providers, to make provision faster
and images smaller.
(delete cluster-provision and cluster-up folders of k8s-1.21)

Cleanup conditions that were needed for k8s-1.21 and lower.

### CODE REVIEW

**Review by brianmcarey — COMMENTED** [review]
@oshoval - I think some of the defaults will have to be updated before we remove the 1.21 provider. For example:
https://github.com/kubevirt/kubevirtci/blob/fe55be77c4413c0bd2f35fe4d69c66e01dc31340/cluster-up/hack/common.sh#L20

**Comment by oshoval** [comment]
Thanks @brianmcarey 
done, with some more cleaning (2 new commits)

**Review by brianmcarey — COMMENTED** [review]
/lgtm

**Comment by oshoval** [comment]
/hold

we have this lane
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/8010/pull-kubevirt-e2e-k8s-1.21-sig-compute-migrations/1546787002895044608

should we bump it to 1.22 / 1.24 ?

**Comment by oshoval** [comment]
@maya-r @awels 
In case you have any lane that still uses the default / 1.21, please bump it to 1.22 

Thanks

**Comment by awels** [comment]
We are good, we have everything at 1.23 or better

**Comment by enp0s3** [comment]
/approve
Thanks @oshoval !

**Comment by oshoval** [comment]
2201 is merged

/hold cancel

**Comment by oshoval** [comment]
/hold

Until CI is stable, because else it will just retest it again and again

**Pull request merged**
