### PR TITLE
kind-1.28: add conformance.json

### PR DESCRIPTION
**Pull request by dhiller**
**What this PR does / why we need it**:

Adds `conformance.json` so that we can run conformance tests with kind provider.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by brianmcarey** [comment]
> /test check-up-kind-1.28

@dhiller  - this looks like it didn't run any of the conformance tests?

**Comment by dhiller** [comment]
@brianmcarey no, since the job didn't use it. I'll modify the check-up-1.28 to use it after this one has landed.

**Review by brianmcarey — APPROVED** [review]
/approve

**Comment by dhiller** [comment]
/hold

sriov is failing - will take a look

**Comment by dhiller** [comment]
SRIOV seemed to start failing after Oct 1st: https://prow.ci.kubevirt.io/job-history/gs/kubevirt-prow/pr-logs/directory/check-up-kind-sriov?buildId=1841094442723840000

**Comment by dhiller** [comment]
Probably related to latest CentOS bump, which seemed to have happened then: https://github.com/kubevirt/kubevirtci/commit/16d40d2a563a61e866cc409c0b2cf1ef66f3c4a4

**Pull request merged**
