### PR TITLE
OKD 4.1.0-rc.0 provider

### PR DESCRIPTION
**Pull request by cynepco3hahue**
Provides the way to provision and run the OKD 4.0 provider via `gocli`.

Goals:
- provide the way to provision and run OKD 4.0 cluster with one master and one worker
- create the background for the integration with KubeVirt CI

Non Goals:
- make provision command work for other providers
- make possible to customize the number of workers(can be covered under followings PR's)

What works:
- integration with docker registry
- integration with NFS server
- connection to the cluster from the local machine

What does not work:
- Ceph integration(CoreOS does not have packaging system)
- Connection to the console from the local machine(needs future investigation)
- Enabling FeatureGates

In general, any additional configuration on the nodes should be done in provision time via customization of ignition configs.

### CODE REVIEW

**Comment by cynepco3hahue** [comment]
@rmohr @slintes The PR is ready for review.

**Comment by cynepco3hahue** [comment]
@davidvossel @slintes Guys, can you please review?
And to make it easier I will describe what customization I do on the installer repository via hacks.
- increase the timeout for cluster initialization from 30 to 60 minutes
- hardcode FQDN `openshift-authentication-openshift-authentication.apps.${var.cluster_domain}` to worker IP, otherwise the installer will fail
- increase kubelet certificate expiration time from 1 day to 1 year

**Comment by slintes** [comment]
hey @cynepco3hahue , I can get this running, and with a bit of DNS configuration and port forwarding I can also access the console. I only have no clue what user/password to use for log in, do you have an idea?

**Comment by rmohr** [comment]
> hey @cynepco3hahue , I can get this running, and with a bit of DNS configuration and port forwarding I can also access the console. I only have no clue what user/password to use for log in, do you have an idea?

For openshift 3 there always were `admin:admin` and `root:root` present.

**Comment by cynepco3hahue** [comment]
@rmohr Under the container `/root/install/auth` should exist a file with credentials, but it makes sense to configure default one.
Can you provider lines that you used to make the console work, I will document it.

**Comment by slintes** [comment]
> @slintes Can you provider lines that you used to make the console work, I will document it.

This is based on what was documented for running OKD with CRC:
 
- edit `/etc/NetworkManager/NetworkManager.conf`, add `dns=dnsmasq` to `[main]` section
- create file `/etc/NetworkManager/dnsmasq.d/okk-kubevirt-ci.conf` with this content:
```
server=/test-1.tt.testing/127.0.0.1
address=/apps.test-1.tt.testing/127.0.0.1
```

With that `test-1.tt.testing` and subdomains are configured to be on localhost. Now we have to forward requests to localhost 443 to the correct service:
- `kubectl port-forward deployment/router-default 8443:443` (using 443:443 doesn't work as user, and root doesn't have KUBECONFIG) 
- `sudo socat TCP-LISTEN:443,fork TCP:localhost:8443`

open `https://console-openshift-console.apps.test-1.tt.testing/`

Maybe this can be made easier, I didn't spend that much time on it.

**Comment by slintes** [comment]
> Under the container `/root/install/auth` should exist a file with credentials

found it :+1:

**Pull request merged**
